### ISSUE TITLE
Potential memory leaks and other issues identified by cppcheck

### ISSUE THREAD

**Issue by Frenzie** [koreader/crengine#106]
```
Checking chmfmt.cpp ...
[../include/lvrefcache.h:155]: (error) Common realloc mistake: 'index' nulled but not freed upon failure
[../include/lvrefcache.h:335]: (error) Common realloc mistake: 'index' nulled but not freed upon failure
[../include/lvptrvec.h:287]: (error) Common realloc mistake: 'rows' nulled but not freed upon failure
[../include/lvptrvec.h:52]: (error) Common realloc mistake: '_list' nulled but not freed upon failure

Checking lstridmap.cpp ...
[lstridmap.cpp:268]: (error) Common realloc mistake: 'm_by_id' nulled but not freed upon failure
[lstridmap.cpp:269]: (error) Common realloc mistake: 'm_by_name' nulled but not freed upon failure

[lvstring.cpp:1225]: (error) Common realloc mistake: 'chunks' nulled but not freed upon failure
[lvstring.cpp:1346]: (error) Common realloc mistake: 'chunks' nulled but not freed upon failure

[lvtinydom.cpp:2619]: (error) Common realloc mistake: 'compressed_buf' nulled but not freed upon failure
[lvtinydom.cpp:2662]: (error) Common realloc mistake: 'uncompressed_buf' nulled but not freed upon failure

Checking pdbfmt.cpp ...
[pdbfmt.cpp:679]: (error) Uninitialized struct member: hdr.recordCount
[pdbfmt.cpp:697]: (error) Uninitialized struct member: hdr.recordCount
[pdbfmt.cpp:698]: (error) Uninitialized struct member: hdr.recordCount
[pdbfmt.cpp:724]: (error) Uninitialized struct member: preamble.compression
[pdbfmt.cpp:721]: (error) Uninitialized struct member: preamble.nonTextRecordStart
[pdbfmt.cpp:728]: (error) Uninitialized struct member: preamble.imageCount
[pdbfmt.cpp:729]: (error) Uninitialized struct member: preamble.imageCount
[pdbfmt.cpp:729]: (error) Uninitialized struct member: preamble.imageDataRecordStart
[pdbfmt.cpp:766]: (error) Uninitialized struct member: preamble.hederLength
[pdbfmt.cpp:761]: (error) Uninitialized struct member: preamble.firstNonBookIndex
[pdbfmt.cpp:837]: (error) Uninitialized struct member: preamble.firstImageIndex
[pdbfmt.cpp:764]: (error) Uninitialized struct member: preamble.mobiFlags
[pdbfmt.cpp:853]: (error) Uninitialized struct member: preamble.compression
[pdbfmt.cpp:856]: (error) Uninitialized struct member: preamble.textLength
[pdbfmt.cpp:851]: (error) Uninitialized struct member: preamble.recordCount
[pdbfmt.cpp:857]: (error) Uninitialized struct member: preamble.recordCount
```

https://github.com/koreader/crengine/blob/15db5195623e5560ad8fc14e6a7dbdf9364cd3c5/crengine/include/lvrefcache.h#L155
https://github.com/koreader/crengine/blob/15db5195623e5560ad8fc14e6a7dbdf9364cd3c5/crengine/include/lvrefcache.h#L335
https://github.com/koreader/crengine/blob/15db5195623e5560ad8fc14e6a7dbdf9364cd3c5/crengine/include/lvptrvec.h#L52
https://github.com/koreader/crengine/blob/15db5195623e5560ad8fc14e6a7dbdf9364cd3c5/crengine/include/lvptrvec.h#L297
https://github.com/koreader/crengine/blob/15db5195623e5560ad8fc14e6a7dbdf9364cd3c5/crengine/src/lstridmap.cpp#L268-L269
https://github.com/koreader/crengine/blob/15db5195623e5560ad8fc14e6a7dbdf9364cd3c5/crengine/src/lvstring.cpp#L1225
https://github.com/koreader/crengine/blob/15db5195623e5560ad8fc14e6a7dbdf9364cd3c5/crengine/src/lvstring.cpp#L1346
https://github.com/koreader/crengine/blob/15db5195623e5560ad8fc14e6a7dbdf9364cd3c5/crengine/src/lvtinydom.cpp#L2619
https://github.com/koreader/crengine/blob/15db5195623e5560ad8fc14e6a7dbdf9364cd3c5/crengine/src/lvtinydom.cpp#L2662

The initial part of the workaround is probably obvious enough. I figure that instead of

```c
index = (LVRefCacheIndexRec*)realloc( index, sizeof(LVRefCacheIndexRec)*indexsize );
```

you do something like:

```c
tmp = (LVRefCacheIndexRec*)realloc( index, sizeof(LVRefCacheIndexRec)*indexsize );
if (tmp) {
  index = tmp;
} else {
  // but what here? free the old value? reuse it?
}
```

**Comment by poire-z** [comment]
The compressed_buf and uncompressed_buf  are mine :) More fun :|

**Comment by poire-z** [comment]
There is this, that is used by some other parts of the code:
https://github.com/koreader/crengine/blob/051e12afdf1ef50298c1504c8a7fd86ae52b9920/crengine/include/lvmemman.h#L40-L48

**Comment by Frenzie** [comment]
Clearly the cppcheck wasn't a matter of CI. :-P Nice find!

**Comment by poire-z** [comment]
This makes the pack/unpack still work as before:
```c
--- a/crengine/src/lvtinydom.cpp
+++ b/crengine/src/lvtinydom.cpp
@@ -2616,7 +2616,7 @@ bool ldomPack( const lUInt8 * buf, int bufsize, lUInt8 * &dstbuf, lUInt32 & dsts
             return false;
         }
         int have = PACK_BUF_SIZE - z.avail_out;
-        compressed_buf = (lUInt8 *)realloc(compressed_buf, compressed_size + have);
+        compressed_buf = cr_realloc(compressed_buf, compressed_size + have);
         memcpy(compressed_buf + compressed_size, tmp, have );
         compressed_size += have;
         if (z.avail_out != 0) // buffer not fully filled = deflate is done
@@ -2659,7 +2659,7 @@ bool ldomUnpack( const lUInt8 * compbuf, int compsize, lUInt8 * &dstbuf, lUInt32
             return false;
         }
         int have = UNPACK_BUF_SIZE - z.avail_out;
-        uncompressed_buf = (lUInt8 *)realloc(uncompressed_buf, uncompressed_size + have);
+        uncompressed_buf = cr_realloc(uncompressed_buf, uncompressed_size + have);
         memcpy(uncompressed_buf + uncompressed_size, tmp, have );
         uncompressed_size += have;
         if (ret == Z_STREAM_END) {
```

(Dunno about the more complex `(T**)`, may be they'll work as simply, but i'm easily frightened when i see too many `&` and `*`)

**Comment by Frenzie** [comment]
No complaints here. :-)

**Comment by poire-z** [comment]
I was actually hoping you would complain with: _hey, let me fix all of them_ :)

**Comment by Frenzie** [comment]
Another one. I must've overlooked it previously because #112 doesn't touch that file.

```
[crengine/include/lvref.h:385]: (error) Reference to temporary returned.
```

https://github.com/koreader/crengine/blob/052637f1f4ca831fd03aafab89df8358d8ca0f49/crengine/include/lvref.h#L381-L387

Does this mean that `LVRef()` is temporary and destroyed before function exit?

**Comment by poire-z** [comment]
Guess it's about the last line:
`return LVRef( new T( *_ptr ) ); `
The `new T( *_ptr )` creates a new local variable. LVRef() gets its reference and returns it, at which point the local variable is destroyed. No idea how to fix that...

**Comment by Frenzie** [comment]
Line 385 is `return LVRef();` though, not the one with new T().

**Comment by Frenzie** [comment]
From #117.
```
[crengine/src/wordfmt.cpp:700]: (error) Memory leak: pucJpeg
```

But it ends with `free()`. False positive?

https://github.com/koreader/crengine/blob/12e884a6531c1e5bfc406a087687f1b0e1ecde34/crengine/src/wordfmt.cpp#L688-L712

**Comment by poire-z** [comment]
May be the possible `return FALSE` at line 696, without any `free(pucJpeg)` in that case.
But It should have noticed it before...

**Comment by Frenzie** [comment]
Running cppcheck on all the files takes like half an hour. I'm only running it on files affected by the current PR so as to be sure(r) that the PR doesn't introduce any regressions. ;-)

**Comment by Frenzie** [comment]
Anyway, I probably just made the mistake of not running it with `--quiet` so that I must've missed some errors/warnings in all the noise. I'd probably better add that on Travis too.

Good point about return false. That's the key. :-)

**Comment by Frenzie** [comment]
Okay, here's all that remains as far as cppcheck is concerned.
```bash
$ cppcheck --quiet -j 8 crengine/src/
[crengine/src/pdbfmt.cpp:771]: (error) Uninitialized struct member: preamble.hederLength
[crengine/src/pdbfmt.cpp:766]: (error) Uninitialized struct member: preamble.firstNonBookIndex
[crengine/src/pdbfmt.cpp:842]: (error) Uninitialized struct member: preamble.firstImageIndex
[crengine/src/pdbfmt.cpp:769]: (error) Uninitialized struct member: preamble.mobiFlags
[crengine/src/pdbfmt.cpp:858]: (error) Uninitialized struct member: preamble.compression
[crengine/src/pdbfmt.cpp:861]: (error) Uninitialized struct member: preamble.textLength
[crengine/src/pdbfmt.cpp:856]: (error) Uninitialized struct member: preamble.recordCount
[crengine/src/pdbfmt.cpp:862]: (error) Uninitialized struct member: preamble.recordCount
```
