### ISSUE TITLE
Width & height limited to 3000

### ISSUE THREAD

**Issue by Frenzie** [koreader/crengine#138]
@poire-z Is there any reason not to increase this to something much more reasonable like 8000, 16000 or 32000?

https://github.com/koreader/crengine/blob/2457f8f07a0c23b2285dd8af6939e28dc04fd5e1/crengine/src/lvdocview.cpp#L3276-L3282

**Comment by Frenzie** [comment]
I only mention those specific values because they're close to common texture sizes.

8192
16384
32767

```
$ glxinfo -l | grep GL_MAX_TEXTURE_SIZE
    GL_MAX_TEXTURE_SIZE = 16384
    GL_MAX_TEXTURE_SIZE = 16384
```

Anyway, it works fine at 32767 and I see no reason not to. It doesn't do anything other than lessen the impact of an annoying artificial limit. Sure, it uses a little more memory *if* you have a larger screen, but that comes with the territory.

**Comment by poire-z** [comment]
I'd see no problem with raising this max screen width and height.
I have no idea what current devices and monitor max w/h are. I live in a tiny world of cheap laptops :)
And I have no idea what this _texture_ thing is about :)

**Comment by Frenzie** [comment]
Current limits are roughly this: https://www.youtube.com/watch?v=Toft6fMvByA

In general use, 3840 × 2160 is common (it wasn't quite yet when I got mine a few years ago) and 5120 × 2880 is not unusual. For KOReader this might be relevant for tablets and some high-end phones. The Samsung Galaxy S8 has only 2960 ×1440 though, just short of the magic 3000.

**Comment by Frenzie** [comment]
PS I would never ever buy one of those. A thousand for a *phone*?! I'll just buy a super fancy new lens for my real camera instead. Or something. Just about anything other than a phone really.

I'd much more seriously consider it for a 5k monitor. I wouldn't, but at least that would last for a decade.
