### ISSUE TITLE
Attribute value case shouldn't matter (for the most part)

### ISSUE THREAD

**Issue by Frenzie** [koreader/crengine#140]
See https://github.com/koreader/koreader/issues/3459#issuecomment-375909783

[classname-case.xhtml.txt](https://github.com/koreader/crengine/files/1844642/classname-case.xhtml.txt)

```html
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title></title>
  <style>
.borderBottom {
  border-bottom: 0.15em solid;
}
.borderBOTTOM {
  border-bottom: 0.15em SOLID;
}
</style>
</head>

<body>
<p class="borderBottom">Should have border-bottom.</p>
<p class="borderbottom">Should <em>not</em> have border-bottom.</p>
<p class="borderBOTTOM">Should have border-bottom.</p>
</body>
</html>
```

### Expected

![screenshot_2018-03-24_18-36-20](https://user-images.githubusercontent.com/202757/37866980-7226b95c-2f92-11e8-8955-33118ac61d2e.png)

### Received

![screenshot_2018-03-24_18-36-04](https://user-images.githubusercontent.com/202757/37866979-71fa1758-2f92-11e8-9953-9642a24dd748.png)

**Comment by poire-z** [comment]
Follow up of https://github.com/koreader/crengine/pull/159#issuecomment-383736672 about this issue here.

I'm refering to your first link of #140: _See https://github.com/koreader/koreader/issues/3459#issuecomment-375909783_

So, is that right?:
- CSS attribute value case should not matter (SOLID = solid).
- HTML attribute value case should matter (borderBOTTOM != borderbottom , so they should use the different css)

But mhhh, you did not make your test case obvious as showing what's breaking :)
The last line, that you are happy to see with a border, has it not because of crengine not mattering `SOLID`, but because it uses for all the css definition for `borderbottom` in lowercase. Just like the 2nd line has it too.

But indeed, crengine does not like `SOLID`.
So, they are 2 bugs: `SOLID` should be treated like `solid`, and classNames `borderBOTTOM` should not use the definition of `borderbottom`?

**Comment by Frenzie** [comment]
Spec: http://w3c.github.io/html/matching-html-elements-using-selectors.html#matching-html-elements-using-selectors

**Comment by poire-z** [comment]
Well, for class names and element IDs, as the lowercase() was added as a fix in the commit you mentionned https://github.com/koreader/crengine/commit/5da0e44909a2526924cb5e1e4ff72e0ba6e3da0e, and as the specs allows for that in `quirks mode`, and we may get to display old HTML, I guess it's safer to keep that.

For css declaration, everything happens in https://github.com/koreader/crengine/blob/master/crengine/src/lvstsheet.cpp, where we could easily change the behaviour.
There are utilities functions:
```
static int substr_compare( const char * sub, const char * & str )
static int substr_icompare( const char * sub, const char * & str )
```

`substr_icompare()` is only used when comparing color names ("red", "blue"...)
`substr_compare()` is used for all the other parsing.

Given:
```
font-weight: bold;
Font-Weight: Bold;
font-size: smaller;
font-size: LARGER;
margin-left: 2EM;
```

`static css_decl_code parse_property_name( const char * & res )` is used to find `font-weight`, and would not accept `Font-Weight` (as it uses `substr_compare()`)

`static int parse_name( const char * & str, const char * * names, int def_value )` is used to find `bold`, and would not accept `Bold` (as it uses `substr_compare()`)

`static bool parse_number_value( const char * & str, css_length_t & value, bool is_font_size=false )`  is used to find `smaller`, and would not accept `LARGER` (as it uses `substr_compare()`), nor would it accept `2Em` nor `3PX`.

**Comment by Frenzie** [comment]
> Well, for class names and element IDs, as the lowercase() was added as a fix in the commit you mentionned 5da0e44, and as the specs allows for that in quirks mode, and we may get to display old HTML, I guess it's safer to keep that.

It's not so much a fix as introducing a big fat bug. >_> Everything I wrote applies: "`.className` should not match `class="classname"`. The performance impact of this buggy behavior is actually significant. Fixing it looks like a slam dunk."

Or to put it another way, should we be more worried about some stray file from the early '90s or about EPUBs?

(The ideal solution, I suppose, would be to have a quirks mode.)

> static bool parse_number_value( const char * & str, css_length_t & value, bool is_font_size=false ) is used to find smaller, and would not accept LARGER (as it uses substr_compare()), nor would it accept 2Em nor 3PX.

They presumably/hopefully don't occur much in the wild, but like I said, CSS is case insensitive by default. It's per-spec and the CSS validator won't throw errors or warnings.

**Comment by Frenzie** [comment]
> For EPUB, we could be strict, as the specs and validators would report errors on them, and say the epub are invalid for any error caused by this change.

But there are no errors. The problem is that `className` is overwriting `classname` and vice versa when they're not supposed to. It'll cause unexpected results but it'll be completely valid either way.

> So, should we just remove the 2 .lowercase() from 5da0e44#diff-1949e62eb9de850feaada4f91fd08fb2 ?

Most likely yes.

> And use substr_icompare() in the 3 parse_*() mentionned above?

Yes, if those wouldn't affect the exceptions I mentioned (font names, path names).

**Comment by poire-z** [comment]
> But there are no errors...

Oh right. I've been writting `class names`, but thinking `IDs` the whole time ... like #Top and #TOP, which could be typos and would make links not work - but as they are already case sensitive, it's would already been happening. I'm less worried about class names typos making these classes not applied.

> Yes, if those wouldn't affect the exceptions I mentioned (font names, path names).

Looks like it should be alright from the code, but I will test.

**Comment by Frenzie** [comment]
> Oh right. I've been writting class names, but thinking IDs the whole time ... like #Top and #TOP, which could be typos and would make links not work - but as they are already case sensitive, it's would already been happening. I'm less worried about class names typos making these classes not applied.

Class names, IDs, potato, potato. ;-)
