### ISSUE TITLE
Minimal HTML document not supported

### ISSUE THREAD

**Issue by Frenzie** [koreader/crengine#141]
I think if the file is named .htm or .html it should be treated as (possibly broken) HTML, period. This is the most minimal valid HTML document you can get:

```html
<!DOCTYPE html>
<title>I am an awesome awesome title in the implicit HEAD.</title>
I am the implicit BODY.
```

[minimal.html.txt](https://github.com/koreader/crengine/files/1844650/minimal.html.txt) (remove the *.txt, of course)

The problem is that the parser is trying to be too clever:
https://github.com/koreader/crengine/blob/1278119f49d6ffef5032ca0de04bd6cdb892f895/crengine/src/lvxml.cpp#L3871-L3880

Within the domain of *valid* HTML it would suffice to add `<title>` to the cleverness, but in the wild obviously that'll often be left out. Other HTML parsers don't try to be clever.

**Comment by poire-z** [comment]
Related: https://github.com/koreader/koreader/issues/1381#issuecomment-217493391
This crashes with `FATAL ERROR #-1: Unknown fatal error`
```html
<!DOCTYPE html>
<title>bla</title>
<style>
p {
text-indent:0.5em;
margin-left:0;
margin-right:0;
text-align:justify;
margin-top:0;
margin-bottom:0.2em
}
h1 + p { text-indent:0; }
</style>
<h1>bla</h1>
<p>blabla</p>
```

**Comment by Frenzie** [comment]
Yes, I went against proper testcase design there. Use a full HTML document for CSS tests lest you accidentally trigger DOM parsing issues. That's always been more of a theoretical thing to me though. :-P
