### ISSUE TITLE
borders not accounted in block height?

### ISSUE THREAD

**Issue by poire-z** [koreader/crengine#160]
Very minor bug to me, but what I thought in https://github.com/koreader/crengine/pull/159#issuecomment-383651145 to be a bug in lvpagesplitter, and later thought it could be worked around in `LVDocView::drawPageTo` by adding +1 to `clip.bottom`, may probably be deeper in the individual block height calculation.

The following snippet (had to use solid/dotted because the color looks strange on my emulator...):
```html
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title></title>
  <style>
.bordered {
  border-top: 1px dotted green;
  border-bottom: 1px solid blue;
  margin: 0px;
  padding: 0px;
}
zzbody { border: 1px solid green; zmargin: 1px;}
</style>
</head>

<body>
a<br/> a<br/> a<br/>
<p class="bordered">Should have some borders at top and bottom.</p>
<p class="bordered">Should have some borders at top and bottom.</p>
<p class="bordered">Should have some borders at top and bottom.</p>
<h1>blah</h1>
a<br/> a<br/> a<br/>
<p class="bordered">Should have some borders at top and bottom.</p>
<p class="bordered">Should have some borders at top and bottom.</p>
<p class="bordered">Should have some borders at top and bottom.</p>
</body>
</html>
```
shows on Firefox as:
<kbd>![image](https://user-images.githubusercontent.com/24273478/39179305-44e15cec-47b4-11e8-8580-d8fb6a0f5bf2.png)</kbd> zoomed: <kbd>![image](https://user-images.githubusercontent.com/24273478/39179193-fe63b8aa-47b3-11e8-9714-2fd734f9f859.png)</kbd>

but on KOReader as (the borders are drawn on each other) (please zoom in ur web browser to see the details)
<kbd>![image](https://user-images.githubusercontent.com/24273478/39179238-19c95e1a-47b4-11e8-8efa-3278f7729e3f.png)</kbd>

If we change `margin: 0px` to `margin: 1px`, it shows as:
<kbd>![image](https://user-images.githubusercontent.com/24273478/39179380-771e94c2-47b4-11e8-8bf9-e09621e4a780.png)</kbd>

If we make the border 2px, the overlap is only 1px:
<kbd>![image](https://user-images.githubusercontent.com/24273478/39179886-c4633a34-47b5-11e8-9060-ffdf4209cfda.png)</kbd>

It looks like there's always 1px being eaten somewhere (which is usually fine as we don't notice this loss as most elements have some margin or padding, or no border), but I can't really figure out where (and I don't feel like digging into the measureBorder and related stuff :)
pinging @frankyifei , who seem to have made some related developments in #16, #23, #49.

**Comment by frankyifei** [comment]
this should be related to the calculation in how the lines are drawn. It was a headache because I had to write the line drawing code. Maybe there is a miscalculation. I will have a look.

**Comment by poire-z** [comment]
I didn't think it was the drawing code, but well, I'm not sure. Just sharing what I observed this morning in case it helps:

I did some printf earlier today (when trying to debug https://github.com/koreader/crengine/pull/159#issuecomment-383651145) in DrawLine, and for the bottom border at bottom of page, which was 2px, it was called 2 times, but because of _clip.bottom, 1 of the 2 calls had `y1 = _clip.bottom == y0` and the for loop was a no-op:
https://github.com/koreader/crengine/blob/779b47fba5f507d27a3b40c0fd11bc4d4dee3265/crengine/src/lvdrawbuf.cpp#L1505-L1519

```c
--- a/crengine/src/lvdrawbuf.cpp
+++ b/crengine/src/lvdrawbuf.cpp
@@ -1504,6 +1507,7 @@

 void LVColorDrawBuf::DrawLine(int x0,int y0,int x1,int y1,lUInt32 color0 ,int length1,int length2,int direction)
 {
+    printf("DrawLine %d %d %d %d vs %d %d %d %d\n", x0, y0, x1, y1, _clip.left, _clip.top, _clip.right, _clip.bottom);
     if (x0<_clip.left)
         x0 = _clip.left;
     if (y0<_clip.top)
@@ -1517,6 +1521,7 @@ void LVColorDrawBuf::DrawLine(int x0,int y0,int x1,int y1,lUInt32 color0 ,int le
     if ( _bpp==16 ) {
         for (int y=y0; y<y1; y++)
         {
+            printf(" drawing 1 lines\n");
             lUInt16 * line = (lUInt16 *)GetScanLine(y);
             for (int x=x0; x<x1; x++)
             {
```
```
DrawLine 9 419 591 420 vs 9 13 591 467
 drawing 1 lines
DrawLine 9 418 591 419 vs 9 13 591 467
 drawing 1 lines
DrawLine 9 443 591 444 vs 9 13 591 467
 drawing 1 lines
DrawLine 9 442 591 443 vs 9 13 591 467
 drawing 1 lines
DrawLine 9 467 591 468 vs 9 13 591 467
DrawLine 9 466 591 467 vs 9 13 591 467
 drawing 1 lines
```

_clip.bottom is set from page.height (in page mode), which is itself made from all the renderBlock heights. I guess these are wrong (always? or only when there are some borders?), and may overlap a small bit.
(It did not happen in scroll mode, because there are no clips done, the the DrawLine that may be outside the last block height is still drawn.)

But it could indeed be that the heights are OK, and there's some miscalculations in the drawing `y`.

(I apologize in advance for your coming headaches :)

**Comment by frankyifei** [comment]
It is not that serious if only one line of the borders is not visible at the end of page. Drawline() is actually drawing a  rectangle. I think we can draw on the last line of drawbuf if we add some code to handle it. like you said, it is working in scroll mode. 
I talked about the two borders overlapped when margin is set to 0 in last reply. It could be over simplicity in the calculation of DrawBorders(). I still can't find it through.

**Comment by poire-z** [comment]
Yes, working around that last line of page is easy:
```c
--- a/crengine/src/lvdocview.cpp
+++ b/crengine/src/lvdocview.cpp
@@ -1777,7 +1777,7 @@ void LVDocView::drawPageTo(LVDrawBuf * drawbuf, LVRendPageInfo & page,
        lvRect clip;
        clip.left = pageRect->left + m_pageMargins.left;
        clip.top = pageRect->top + m_pageMargins.top + headerHeight + offset;
-       clip.bottom = pageRect->top + m_pageMargins.top + height + headerHeight
+       clip.bottom = pageRect->top + m_pageMargins.top + height + headerHeight + 1
                        + offset;
        clip.right = pageRect->left + pageRect->width() - m_pageMargins.right;
        if (page.type == PAGE_TYPE_COVER)
```
but it's just a workaround (and indeed, so minor that it's not that serious to need this workaround - I felt just like having a look for a quick fix to prevent other misinterpretations of tests :)
But it does not fix the borders overlaping, which is the root cause (and also, not a serious bug that needs fixing, with the risk of messing with other things).
I mentionned just in case some quick solution jumped at you :)

But couldn't it be that like in here (and may be other places):
https://github.com/koreader/crengine/blob/779b47fba5f507d27a3b40c0fd11bc4d4dee3265/crengine/src/lvrend.cpp#L1775-L1801
you're `AddLine()` heights for padding and margin, top and bottom, but you're not doing it for borders?

**Comment by frankyifei** [comment]
Addline should only affects paging. Border width is added in paddings in the beginning so it is already there.

**Comment by poire-z** [comment]
Oh, right, sorry, didn't see that done in the far right :)
https://github.com/koreader/crengine/blob/779b47fba5f507d27a3b40c0fd11bc4d4dee3265/crengine/src/lvrend.cpp#L1653-L1656

**Comment by poire-z** [comment]
> this could be related to the calculation in how the lines are drawn. It was a headache because I had to write the line drawing code. Maybe there is a miscalculation. I will have a look.

@frankyifei : You may be right, I think it's probably in the DrawBorder code that there is a problem.

https://github.com/koreader/crengine/blob/fe91ee062b2160defad6098fadafe014e16d11e8/crengine/src/lvrend.cpp#L2100-L2513

In there, if we look at how the bottom border is drawn, we have:
```c
leftpoint1=lvPoint(x0+doc_x,y0+doc_y+fmt.getHeight())
leftpoint3=lvPoint(x0+doc_x,doc_y+y0+fmt.getHeight()-bottomBorderwidth)
rightpoint1=lvPoint(x0+doc_x+fmt.getWidth(),doc_y+y0+fmt.getHeight())
        case css_border_solid:
            for(int i=0; i<leftpoint1.y-leftpoint3.y; i++)
            {drawbuf.DrawLine(
                              leftpoint1.x+i*leftrate, // start x
                              leftpoint1.y-i, // start y
                              rightpoint1.x-i*rightrate, // end x
                              rightpoint1.y-i+1, // end y
                              bottomBordercolor,dot,interval,0);}
```
If we take an example with x0, doc_x, y0, doc_y are all zero, and the object is a 8px image, with a border top of 1px and a border bottom of 1px, we would have a fmt.getHeigth() =10.
And we should be drawing a top border line at y=0 and a border bottom line at y=9.
With the above code snippet, we are `DrawLine(start_x, 10, end_x, 11)`, so we are drawing a line at y=10

I think it could be as simple as, in all the above code:
replace all the `fmt.getHeight()` with `fmt.getHeight()-1`
(and probably the same with `fmt.getWidth()`, to be replaced with `fmt.getWidth()-1`?)

Does that look like the right thing to do for you?

(This code is quite tedious to read and I don't want to have to go thru each line to check if the x/y are right...:)

**Comment by frankyifei** [comment]
you could be right. You can test what you suggested and see how it goes.

**Comment by poire-z** [comment]
I've been testing this since a few hours, with a few wikipedia articles and another book with some borders, and it looks fine (the only change is that the occasional missing bottom borders are now visible).
I'll PR that in a few days so it can be a lone change in a nightly.

**Comment by poire-z** [comment]
OK, proposed changes in #211.
