### ISSUE TITLE
implementing dpi-based css units

### ISSUE THREAD

**Issue by poire-z** [koreader/crengine#161]
Related: #46, https://github.com/koreader/koreader/issues/1010 https://github.com/koreader/koreader/issues/3189

Units supported:
https://github.com/koreader/crengine/blob/1acfd0020c97157e4463c6431c9e5ad2b9a7b658/crengine/include/cssdef.h#L160-L174

The code where to implement these seems limited to lvrend.cpp:

https://github.com/koreader/crengine/blob/1acfd0020c97157e4463c6431c9e5ad2b9a7b658/crengine/src/lvrend.cpp#L988-L1011
Similar to previous, but modify val in-place:
https://github.com/koreader/crengine/blob/1acfd0020c97157e4463c6431c9e5ad2b9a7b658/crengine/src/lvrend.cpp#L2639-L2667

In these, `base_px` is usually the width of the container, the width in px that can be considered 100%.
`base_em` is usually `currentnode->getFont()->getSize()`.
KOReader could provide to crengine the current `screen_dpi`, that could be set as a global and used in these.
I would welcome any formula (based on some of these 3 parameters) to use for each not supported unit :)

Also, I wonder if it's the right thing to do to use the Screen DPI set in koreader: I usually set this one just for menu items heights and icons width to look and spread nice.
It is used to scale the default font size given to crengine according to:
`self.ui.document:setFontSize(Screen:scaleBySize(self.font_size))`
https://github.com/koreader/koreader-base/blob/2faf0891403033390b2b652a9a5d24ba489f2298/ffi/framebuffer.lua#L256-L268
So, then, in crengine, I choose the font size that I want (so, losing any link to the formula).
So, I wonder it we should use that DPI as-is, or make it go thru scaleBySize() which can round it a bit, or just use some hardcoded one unrelated to what is set in KOReader :)

(I suck at that DPI business, I don't mind not understanding it all, or having it pixel/unit perfect - I just find it sad that these units are ignored - so just tell me what to do :)

Of interest, may or may not need modifying:
https://github.com/koreader/crengine/blob/1acfd0020c97157e4463c6431c9e5ad2b9a7b658/crengine/include/cssdef.h#L228-L231
https://github.com/koreader/crengine/blob/1acfd0020c97157e4463c6431c9e5ad2b9a7b658/crengine/src/lvrend.cpp#L2723-L2749
Parsing of css:
https://github.com/koreader/crengine/blob/1acfd0020c97157e4463c6431c9e5ad2b9a7b658/crengine/src/lvstsheet.cpp#L335-L361

Other sections of lvrend.cpp to consider (for all units or some do not make sense?):

https://github.com/koreader/crengine/blob/1acfd0020c97157e4463c6431c9e5ad2b9a7b658/crengine/src/lvrend.cpp#L1051-L1081

https://github.com/koreader/crengine/blob/1acfd0020c97157e4463c6431c9e5ad2b9a7b658/crengine/src/lvrend.cpp#L1318-L1333

https://github.com/koreader/crengine/blob/1acfd0020c97157e4463c6431c9e5ad2b9a7b658/crengine/src/lvrend.cpp#L2814-L2841

**Comment by Frenzie** [comment]
Incidentally, the above testcase has some odd results. Any decimal value like `.3px` or `.8px` renders as if it were `2px`. I'm guessing that must be the default value and that `.3px` is dropped as an unsupported value?

**Comment by poire-z** [comment]
For simplicity, let's keep for crengine 1css px = 1 physical screen px :)
There are many `border: 1` in css to just implement some thin border - I would not want it to become 3px on my 300 dpi GloHD, or to depend on the font size I set.

I simply want for now to implement _something_ for those not supported that currently returns 0 and has no effect.
I'm not aiming at having pixel/spec perfect rendering (and I don't mind if `border: 1cm` does not make 1cm on my Kobo screen, I'd just like it to not make 0cm :)

> The only practical question is whether the "font size" setting should actually set the font size or instead the DPI for crengine

Turned around: as we are given in the function the current font size as `em`, can we map that back to some dpi and derive something from `em` for the other units ?
And if we wanted 1cm to look like 1cm, the DPI shouldn't be allowed to be set and changed: it should be fixed according to guessed DPI of the device physical screen?

**Comment by Frenzie** [comment]
> I simply want for now to implement something for those not supported that currently returns 0 and has no effect.

In that case why make it difficult? 1px = 1pt, close enough. Or if you want to be a little bit more precise, as I said 1px = 1/96 inch.

1in = 2.54cm = 25.4mm = 72pt = 6pc

1in = 96px
2.54cm = 96px
25.4mm = 96px
72pt = 96px
6pc = 96px

> I'm not aiming at having pixel/spec perfect rendering (and I don't mind if border: 1cm does not make 1cm on my Kobo screen, I'd just like it to not make 0cm :)

A unit like `cm` should normally only be used in print styles. Applying it on screen is an author error. But in any case, that'd be 1/2.54*96=38px.

> And if we wanted 1cm to look like 1cm, the DPI shouldn't be allowed to be set and changed: it should be fixed according to guessed DPI of the device physical screen?

We only want it to do (roughly) that by default. Zoom changes everything. ;-)

**Comment by poire-z** [comment]
> 1in = 96px
2.54cm = 96px
25.4mm = 96px
72pt = 96px
6pc = 96px

I like when things are that clear :) and no DPI involved! I'll have a try.

> Rem is the same as em, except instead of parent_style->font_size.value you'd need root_element_style->font_size.value.

Simple to add in include/cssdef.h and in the various `case:`, not sure about how to reach the default/root font size, if we can from these functions, or if it should be passed in as an additional parameter by the callers. Is `rem` popular and makes sense to have ?

> (What was it you said the root element was? Element 12 or 13 or something? :-P)

16+1 :) but there are functions to get it so we don't look like we're too clever and know the internals :)

**Comment by Frenzie** [comment]
> Is rem popular and makes sense to have ?

Very and yes. For many purposes it's what you always wished em was.

**Comment by poire-z** [comment]
Do you happen to know about an existing good test case/visual validation sample for these new css units? (or can quickly make one :)

**Comment by Frenzie** [comment]
There are the official CSS test suites. I imagine they cover at least the basics. In this case not visually though.

http://test.csswg.org/suites/css-values-3_dev/nightly-unstable/

http://test.csswg.org/suites/css-values-3_dev/nightly-unstable/html/absolute-length-units-001.htm

**Comment by poire-z** [comment]
If in CSS world, `1 px` should no more be 1 px :) , and if we follow as a first step your above simple factors to get `css px` out of other units, then, it would only be a matter as a second step of multiplying the final `css px` by some DPI based factor (1, 2 or 3) to return an ultimate physical px.
Could it be as simple as that if we later want to add this 2nd step?

**Comment by Frenzie** [comment]
Logically speaking I would prefer to make the relationships between the units themselves a little more self-explanatory within the code. For example, `1pc` = `12pt`. `12pt` = `1/72inch`. On the flipside, it's probably ever so slightly more efficient to shortcut the calculation plus some explanatory comments.

> some DPI based factor (1, 2 or 3) 

Or 6 or 2.7 or 3.14. :-)

> Could it be as simple as that if we later want to add this 2nd step?

If the pixels are sufficiently fractional. `0.5 CSS px`\*`6`=`3 physical px`. But if they're rounded too early you'd get something closer to `0.5px` → `1 CSS px`\*`6`=`6 physical px`. I don't think that should normally require any doubles but it's no place for integers. Luckily we all have hardware floating point support (except on legacy Kindle).

As an aside, we could check how Firefox and Blink/WebKit go about this. Quick search result (looks a lot like what I envisioned): https://github.com/servo/servo/blob/9a900ef019cd643bff961d7b20db6da69f3edb29/components/style/values/specified/length.rs#L28-L49

(also see)
https://github.com/servo/servo/blob/087bd20b6d4e61fd54b71ed42a0ce757f993bb66/ports/geckolib/glue.rs#L3884-L3893
https://github.com/servo/servo/blob/9a900ef019cd643bff961d7b20db6da69f3edb29/components/style/values/specified/length.rs#L271-L295

**Comment by cramoisi** [comment]
This will save loads of time, like converting any .doc into .epub (ms put pt values, if not cm everywhere)

While you are at this I have a suggestion (but don't know if it's interesting or not)  : let's say I got a value like `text-indent: 12` without unit. What will be the default unit ? It could be cool to have one (if it's not already the case).

**Comment by Frenzie** [comment]
The correct behavior is to drop it.

**Comment by cramoisi** [comment]
I thought so ! I asked only because of calibre (which can't rename the unit but can divide, add, multiply a value...)

**Comment by poire-z** [comment]
Any length with no unit is currently dropped bt crengine (the only case is when `text-indent: 0`, where it's considered `0px`).
(Even though I looked at this code quite a bit the last days, I really thought it was treating lengths with no unit as pixels (and I would have insisted to not drop that behaviour ! :) till I tested... I even thought I would have left some numbers without unit in the wikipedia stylesheet, but did not... I even thought I read on some urls yesterday that no unit should be considered pixels, but can't find that anymore .. am I really getting that old?)
The fact is I have many no-unit css in some of my little web/cgi script works:
```
    padding: 5;
    margin: 0;
    line-height: 1.15
```
and that padding gets applied by Firefox! May be again, some quicks mode?
If I remove this from my test html, Firefox do applies no-unit css:
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
```

I dunno then, could be good to fallback to `px`, as it's obviously some very human mistake :)

Then, what about `line-height:` ? https://www.w3schools.com/cssref/pr_dim_line-height.asp _A number that will be multiplied with the current font-size to set the line height_. crengine seems to do that in one of the snippets of first post, but it looks like it would not be considered px by the generic css parsing code then... Should some others be treated differently?

Some links for rerefence about these length units:
https://developer.mozilla.org/en-US/docs/Web/CSS/length
https://www.w3.org/Style/Examples/007/units.en.html

**Comment by Frenzie** [comment]
> May be again, some quicks mode?

For IE and WebKit/Blink, quirks mode means as much as an IE4/5 compatibility mode, whereas it's traditionally closer to a Netscape 3/4 compatibility mode for Firefox. Recently quirks mode has become more formalized. The tl;dr version is that no DTD means quirks mode.

> The fact is I have many no-unit css in some of my little web/cgi script works:

line-height should be used without units. That's unrelated to properties which don't accept plain numbers and should *not* emulate IE4's broken behavior.

> Should some others be treated differently?

Yes, you also have `<number>` in `:nth-child(<number>)`, `:nth-of-type(<number>)`, etc. (The CSS spec might specify that they should be `<integer>`, as in no decimals. You'd have to check.) Otoh line-height is the only one that isn't obvious, however.

> Some links for rerefence about these length units:

When you want to understand something the CSS1 spec is often the place to go:
https://www.w3.org/TR/CSS1/#notation-for-property-values (not sure if it distinguished between `<number>` and `<integer>` yet)

The CSS3 spec removes room for interpretation, but can quickly become borderline incomprehensible in doing so. Anyway, here's the CSS3 equivalent: https://drafts.csswg.org/css-values-3/#numeric-types (virtually the same as in CSS 2, not too bad in this case)

**Comment by poire-z** [comment]
Done in #213.
