### ISSUE TITLE
Ordered list not rendering as expected on first load (Html401/10_2-BF-01)

### ISSUE THREAD

**Issue by Frenzie** [koreader/crengine#177]
This is another weird issue that disappears after changing something.

![screenshot_2018-05-05_12-33-52](https://user-images.githubusercontent.com/202757/39662364-a5931b7a-5060-11e8-9ecb-3cda04aa141a.png)

**Comment by Frenzie** [comment]
Also applies to 10_3-BF-01 and, well, basically all of them. Rendering may or may not be correct on first try but either way it's *different* after doing something like toggling embedded styles on/off.

![screenshot_2018-05-05_12-42-54](https://user-images.githubusercontent.com/202757/39662448-d8599b8c-5061-11e8-86cf-6cb583ae6bcd.png)

**Comment by poire-z** [comment]
Can't reproduce any of that, even with a vanilla settings.reader.lua...

**Comment by Frenzie** [comment]
+ getting rid of .sdr?

**Comment by poire-z** [comment]
Yep :|

**Comment by poire-z** [comment]
Would this be fixed with #226 ?

**Comment by Frenzie** [comment]
On a completely unrelated note, clear readers' caches breaks the ability to build the emulator without manually removing the cache folder.

**Comment by Frenzie** [comment]
Anyway, I'm currently having trouble reproducing the problem on my current laptop checkout from July 29. Perhaps some other style-related change accidentally worked around the problem?

**Comment by Frenzie** [comment]
Well, it seems to be, so closing.
