### ISSUE TITLE
Question: how to use @import in crengine

### ISSUE THREAD

**Issue by Frenzie** [koreader/crengine#179]
@poire-z Okay, so parsing of `@import` is obviously suboptimal, but I can't figure out how to make it work.

https://github.com/koreader/crengine/blob/5cd06ecaa4dca503947e3b863ea5eb569df8d5ec/crengine/src/lvstsheet.cpp#L2619-L2669

Looking at that code, something like `@import 'user.css';` would not work. So far so good, I could fix that. But more problematically, `@import url("user.css");` doesn't seem to work either.

Do you have any idea what scenario is currently supported, exactly?

**Comment by poire-z** [comment]
No, never looked at that (and it looks like it would only @import once).
(and we'll soon have CSS snippets to inject stuff, which should be more practical that hacking the crengine styles)

**Comment by cramoisi** [comment]
@Frenzie don't know how it would apply here, but I remember reading that years ago (was mostly interesting to me for figuring out the order) : 

http://www.stevesouders.com/blog/2009/04/09/dont-use-import/

**Comment by Frenzie** [comment]
@cramoisi It doesn't apply. It's saying some old version of IE has an issue when using @import in combination with `LINK` while loading resources over the HTTP protocol. It doesn't mention it by name, perhaps because the linked page is close to a decade late to the party or because it's talking about a specific aspect, but basically the author describes a method to trigger the well-known "flash of unstyled content" problem: https://en.wikipedia.org/wiki/Flash_of_unstyled_content

In an online context it's generally recommended to minimize your stylesheets to prevent increasing the number of parallel connections anyway, which means (automatically, of course) flattening your stylesheets into one minimized file. That speeds up loading times with or without weird additional browser bugs.

In this case it seems to me that using generic @import mechanicms (particularly if already implemented) is the same in practice as hard-coding trying to load a user.css.

**Comment by cramoisi** [comment]
I thought so, sorry ! (I reread it since I posted , has to do it in reverse :p )

**Comment by poire-z** [comment]
Pes-specs, `@import` is only allowed at top of a stylesheet - only `@charset` is allowed before.
This bit of code seems to work with processing multiple imports in embedded stylesheets, at least at parsing crengine specific handling of multiple `<link href=...>` which ends up like this:
![image](https://user-images.githubusercontent.com/24273478/132250074-be59c5c8-210a-4c2a-946d-249c7a203d3f.png)

But for processing our user agent stylesheet (epub.css, html5.css), it only process ONE `@import`, the first one, and don't handle the next ones if any. Thought about fixing that, but didn't care enough.
Then styletweaks are just appended to this user agent stylesheet content, so no `@import` then, just plain string appending.

So, don't know in which context you were experimenting 3.5 years ago :)

**Comment by Frenzie** [comment]
Probably the context of .html, couldn't say besides that.
