### ISSUE TITLE
Hyphenation sometimes splits „rz” in Polish

### ISSUE THREAD

**Issue by KrzysiekJ** [koreader/crengine#214]
The word „pancerzach” gets split on „rz” when hyphenation is set to Polish. This is a glaring error, as „rz” is a distinct sound in Polish (an exception: „Tarzan”).

Refs #77, cc @robert00s.

**Comment by cramoisi** [comment]
hi @KrzysiekJ that could be easily corrected, but the fact is I can't read Polish. Can you give me some example like i'm six year old ?


(will be easier for me if you do them like this :  )
bon-jour
souf-fler
té-lé-vi-sion


if you want you can open the polish dictionary (utf-8) and look it for yourself, the rules are like this : 

a odd number is where you can cut (a higher number will override rules)
a even number is where you can't cut (a higher number will override rules)
a space for the beginning a word (no space is a wildcard)
a space for the end of a word (no space is a wildcard)

**Comment by cramoisi** [comment]
@robert00s (if you got examples too, I'll take them)

**Comment by cramoisi** [comment]
Here is the rules which authorize the cut : (tarzan is there)

<pattern> supe2r5z2b</pattern>
<pattern> ta2r7zan</pattern>
<pattern>cu2r7zon</pattern>
<pattern>e2r5zac</pattern>
<pattern>fo2r5zac</pattern>
<pattern>ma2r5z1ł</pattern>
<pattern>ma2r5z1l</pattern>
<pattern>ma2r5z1n</pattern>
<pattern>mie2r5z1ł</pattern>
<pattern>mi1e2r5zi1</pattern>
<pattern>mu2r7zasic2h3l</pattern>
<pattern>sko2r5zoner</pattern>

**Comment by cramoisi** [comment]
your word, pancerzac is ruled by <pattern>2r2z1c</pattern>, so it's cut. I would only add a rule for the word as all seems ok, or you have some other examples for making a wider pattern.

**Comment by cramoisi** [comment]
But your statement seems strange because pancer : armored / zach : reaper ; the rule for constructed words is to cut between them (thanks translator).

**Comment by poire-z** [comment]
Closing for lack of feedback.
