### ISSUE TITLE
Potentially interesting commits about broken files

### ISSUE THREAD

**Issue by Frenzie** [koreader/crengine#227]
>  Fixed stack corruption on broken files: index out of range in PreProcessXmlString() in lvxml.cpp.
>
> Added few safety checks in lvxml.cpp.

> Fixed UTF-8 encoding/decoding according Unicode Standard. 

https://github.com/buggins/coolreader/pull/33

Plus this fix for the first commit https://github.com/buggins/coolreader/pull/35

**Comment by Frenzie** [comment]
Also https://github.com/buggins/coolreader/pull/34

I do seem to get a crash on the testcase there when trying to interact with the program.

**Comment by poire-z** [comment]
Included in #232.
