### ISSUE TITLE
avoid new line before : ? ;  (and so on) in french

### ISSUE THREAD

**Issue by cramoisi** [koreader/crengine#235]
@poire-z : I don't know if you get this but in french, as there is a space before some punctuation and because the nbsp space doesn't work right, it's not uncommon to have a new line before them. (I usually replace them with fine space within calibre before reading to avoid this).

```
([«])(\u00a0|&#160;)|(&#160;|\u00a0)([;:!?»])
\1\u202F\4
```

**Comment by poire-z** [comment]
I get that sometimes, but it's very rare.

I did something to avoid that, not in crengine, but in the textboxwidget stuff that is used to display dictionary and wikipedia results.
https://github.com/koreader/koreader/blob/c8d19b310c24888bf0c2e24a6865b8477fc1969f/frontend/util.lua#L231-L308

I'll see if something like that could be made into crengine.

**Comment by cramoisi** [comment]
@poire-z Great ! usually, in french, it's `&nsbp;, \u00a0 or &#160;` which is used ; the space is very rarely used. But it doesn't prevent the CR.

**Comment by poire-z** [comment]
Are you sure ?
Because if `&nbsp;` wasn't working as expected (=not being candidate for line split), we would get a lot more bad wraps.
(Aren't you using floating puncutation - which might be buggy in many ways?)

**Comment by cramoisi** [comment]
Pretty sure. I haven't the issue since a long time ago as I regexp all my books with the lines in the first post (these are also use by roger64 on mobilread for the same reason as me). I don't use floating puctuation and I installed Koreader to a friends' kobos 1 week ago and they experience the issue. Floating is default disabled.

![40619448_689474984750802_7468806149010096128_n](https://user-images.githubusercontent.com/28014131/45488350-6c362a80-b761-11e8-82dd-3a69fe3017d4.jpg)

**Comment by cramoisi** [comment]
@poire-z [ttps://www.mobileread.com/forums/showthread.php?t=285622&highlight=nbsp](https://www.mobileread.com/forums/showthread.php?t=285622&highlight=nbsp)

I got this problem since day 1 ; I have no problem to use calibre to correct this, but in fact I can't ask other people to do the same :/

**Comment by poire-z** [comment]
And you are sure there is a nbsp inside the `simple :` ?
I'm supposed to have fixed that in #70 (discussion in https://github.com/koreader/koreader/issues/2806) :|

Just to be sure, if you can, can you check how it behaves:
- first, with kerning method not enhanced (without the new harfbuzz) - or confirm you and your friend were not using it
- with a nightly before august 22 (before the many upstream fixes, which include [this](https://github.com/koreader/crengine/commit/2f62ed8fd0f1852afa6fc1a89d99a3d37b03acd2) - but this code is not supposed to be used by us for line splitting). (if you have a good test case, you could check on the emulator by reverting the fist chunk, if it changes anything...)

**Comment by cramoisi** [comment]
@poire-z : sorry for the delay ; will test it tomorrow if I can (I just got an unexpected turn in my life some weeks ago and I'm struggling to get some time back for myself)

**Comment by poire-z** [comment]
@cramoisi : done in #237, for real space chars (as I'm pretty sure it works already fine when a `&nbsp;` is used).

But now that we have a `View HTML` in the text selection menu, I'd really like you to check in the books where you experienced this problem what's the HTML where it happens.
You should see `&nbsp;` displayed as `␣` in the `Switch to debug view` view, so if you don't, they are not there :)
As just before the "Et s'il n'y est plus" in:
<kbd>![image](https://user-images.githubusercontent.com/24273478/46608307-a0083400-cb04-11e8-89fd-d904fea00064.png)</kbd>
