### ISSUE TITLE
Potentially interesting sidestream commit

### ISSUE THREAD

**Issue by Frenzie** [koreader/crengine#242]
@poire-z I haven't really looked at it but perhaps this contains some stuff of interest: https://github.com/buggins/coolreader/pull/56/commits/051a7cf45ffd5f4602190a5f8e175437942fc6b1

Also there's some stuff about rounded corners on phones:

https://github.com/buggins/coolreader/commit/d441a24de74f03b60e6c56c42d1480d896f2b530
https://github.com/buggins/coolreader/commit/158e1dd47c28e46d5cb0ff4372e553c22a466848

More of a note to self (or at least probably not so much to you ;-) ), but I also noticed there's some stuff in there about E Ink on Android:

https://github.com/buggins/coolreader/blob/a39b917f8806cbc2cb442d3ee3460ed871038297/android/src/org/coolreader/crengine/EinkScreen.java

With notably Tolino in https://github.com/buggins/coolreader/commit/d3a57ae9492a7142bc444beedb5c62ba5bd1f9ec#diff-eb9f41308b9e99ff125b58e91f174d31

**Comment by poire-z** [comment]
Yep, first commit should solve most of the clang-tidy warnings, so we should probably get it (once it's merged and tested upstream).

The "rounded corners" ones seem to just add some left & right margin to the top status bar. May be not worth the effort (would additionally need all the config and glue to pass stuff from frontend to base to crengine), rounded corners users could as well stick to our bottom status bar :)

**Comment by Frenzie** [comment]
@poire-z 

```
https://github.com/buggins/coolreader/pull/61
```

**Comment by poire-z** [comment]
Mostly a followup to the previous HB enhancement you linked to in #247.

**Comment by poire-z** [comment]
Yep, looks like nothing for us :)

**Comment by virxkane** [comment]
> Saying a commit fixes some crash without saying how one reproduces said crash seems less helpful than it could be. :-) 

On Google Play Developer Console no such info (no logcat, no other usefull info), but only stacktrace without coredump.
Yes, this is hard way :)

**Comment by Frenzie** [comment]
@virxkane I suppose logcat might expose private info. :-)

**Comment by Frenzie** [comment]
@poire-z https://github.com/buggins/coolreader/pull/77 also works for us

**Comment by poire-z** [comment]
OK, it applies cleanly without any manual tweak and works. Let's cherry pick it up when it's merged upstream (so the cherry picked hash stays valid).
(And nice to see a fb2 with footnotes, and see that I didn't break them :)
