### ISSUE TITLE
HB stuff

### ISSUE THREAD

**Issue by Frenzie** [koreader/crengine#247]
@poire-z 

Mostly just a toggle which we already have, but that HB for kerning only could be interesting?

https://github.com/buggins/coolreader/pull/58 + https://github.com/buggins/coolreader/pull/61

**Comment by poire-z** [comment]
Dunno. I'm still not really sensible to kerning and hinting changes :) so I can't say much.

HB kerning without ligatures would still bring something interesting vs FT kerning ?
There's also the whole #230  that I didn't really follow, but i understood @NiLuJe ended up not really happy with the HB/hinting interaction.
There was also https://github.com/koreader/crengine/pull/230#issuecomment-414798538 to speed things up.

I also remembered you said cre with FT kerning looked like bad newspaper. You haven't said if your feeling changed after we had HB :)

(Anyway, won't be able to work on that before next year, so anyone feel free to have a got at integrating it if it feels interesting.)

**Comment by Frenzie** [comment]
Well yeah, "enhanced" looks significantly better. I definitely think of proper kerning as the main benefit of HB and ligatures more like an added bonus.

If proper kerning can be significantly sped up through cache then that could be interesting on slower devices, perhaps to replace the "fast" FT kerning.
