### ISSUE TITLE
epub.css: update to play better with publishers EPUBs?

### ISSUE THREAD

**Issue by poire-z** [koreader/crengine#294]
I'll soon be PR'ing some toggable new block rendering code, that should fix/implement some of the things discussed in #234 (collapsing margins, better page splitting) and introduce some new stuff (limited float support, block width & height...):

<kbd>![image](https://user-images.githubusercontent.com/24273478/59287155-624e4300-8c71-11e9-9aa9-1412c5f9ca20.png)</kbd>

I have to keep the "legacy" code as an option, and stick to it on previously opened books to not mess with their bookmarks/highlights, as floats would introduce new elements in the DOM and could mess xpointers.
New books will open with the one among the other we will decide on.
(These little names flat/book/news/web are just short names that fit in a toggle and sound better than just 1/2/3/4/5 or a progress button bar - we may find better names.)
Anyway, there will be no new `cre_dom_version`, so we'll be allowed to select another mode, even on old books.

I'll be also adding (mostly for use in the Wikipedia epub css) a new private CSS property, that can be used in a declaration that way:
```css
div.thumb {
    border: dotted 1px black;
    margin:  0.5em 2.5em 0.5em 2.5em;
    -cr-only-if: legacy;
      page-break-before: always
    -cr-only-if: enhanced;
      page-break-before: auto
    -cr-only-if: full-featured;
      color: green;
    -cr-only-if: -ensure-style-width float-floatboxes;
      color: blue;
    -cr-only-if: -ensure-style-width; /* - negate */
      background-color: yellow;
}
```

So, I came to think we have a chance with this to introduce some changes/fixes in our [epub.css](https://github.com/koreader/crengine/blob/master/cr3gui/data/epub.css), that may be we wouldn't have dare doing previously because people are used to the historical koreader styles.

Because there are a few things in our epub.css that are not optimal, that may be were chosen in the past to make simple html files look nice, but that add strange things when they play with publishers' CSS in EPUBs which expect a normal web browser stylesheet as the base.

I often end up enabling a few style tweaks to get that normal base back, mainly the "Generic web browser paragraph style" and the "Avoid blank page on chapter start", which reverts:
https://github.com/koreader/crengine/blob/37e29d42f74e39d3667f372c8fe4fd04085e07e4/cr3gui/data/epub.css#L25-L26

The `page-break-before: always` on H1 H2 H3 is a bit hard to defend, as publishers may use them for various level of heading in a same chapter (and some even for the Author Title Editor triplet on a cover page, where they don't expect a page break!).
The `text-align: center;` on H1 H2 H3 H4 H5 H6 is also a design choice, but may be not the best.

For our P:
https://github.com/koreader/crengine/blob/37e29d42f74e39d3667f372c8fe4fd04085e07e4/cr3gui/data/epub.css#L41-L46
vs web browsers P:
```lua
            id = "paragraph_web_browser_style";
            title = _("Generic web browser paragraph style"),
            description = _([[
Display paragraphs as browsers do, in full-block style without indentation or justification, discarding KOReader's book paragraph style.
This might be needed with some documents that expect this style as the default, and only use CSS when it needs to diverge from this default.]]),
            priority = -1,
            css = [[
p {
    text-align: left;
    text-indent: 0;
    margin-top: 1em;
    margin-bottom: 1em;
}
            ]],
```
it's a bit harder to decide. I guess I like our text-justify and our zero-margin, but our text-indent (that I like too in generic paragraphs) often introduces an unwanted indent in table cells.

Anyway, we could decide to change a bit of them by using this new `-cr-only-if: legacy;` in our epub.css so people can still get the "old" style by just tapping on "legacy" - while we would get more adequate styles with all the new modes. We could end up with something like:
```css
/* Headings */
h1, h2, h3, h4, h5, h6 {
    margin-top: 0.7em;
    margin-bottom: 0.5em;
    font-weight: bold;
    text-indent: 0;
    hyphens: none;
    -cr-only-if: legacy:
        text-align: center;
}
h1, h2, h3 {
    page-break-inside: avoid;
    page-break-after: avoid;
    -cr-only-if: legacy:
        page-break-before: always;
}
/* Block elements */
p {
    text-align: justify;
    margin-top: 0;
    margin-bottom: 0;
    -cr-only-if: legacy:
        text-indent: 1.2em;
}
```
With possibly some style tweak to bring them back (as a whole, or individually).

It would still be a bit of a mess among our style tweaks, as some of those would not really apply, or would need more text explaining that they works only on old or on new modes...

Any thoughts?
Ideas of what needs an update in our epub.css?

Pinging @Frenzie @NiLuJe @houqp @frankyifei and our usual EPUB lovers & issuers @cramoisi @robert00s @Eduardomb22 @gerhaher

**Comment by Frenzie** [comment]
> The page-break-before: always on H1 H2 H3 is a bit hard to defend

Before H1 seems fairly sensible, H2 much less so, H3 quite the opposite. (Except that you'd prefer H3 not to be orphaned.)

> it's a bit harder to decide. I guess I like our text-justify and our zero-margin, but our text-indent (that I like too in generic paragraphs) often introduces an unwanted indent in table cells.

You (might) know my opinion: it should be `p+p {text-indent:1em}` (or `1.2em`, whatever). That'll work to prevent any unwanted indents in tables just the same as anywhere else (e.g., after a heading, after a list, after a blockquote, etc., etc., etc.).

**Comment by Frenzie** [comment]
PS I don't really understand all of these different render modes. Except possibly for the page overflow it sounds like I just want web and nothing but web (okay, and legacy).

**Comment by Frenzie** [comment]
PPS Regarding `p+p {text-indent:1em}` being the way to go.

https://en.wikipedia.org/wiki/Paragraph#Typographical_considerations

> Professionally printed material in English typically does not indent the first paragraph, but indents those that follow. For example, Robert Bringhurst states that we should "Set opening paragraphs flush left."[3] Bringhurst explains as follows:
>
>>    The function of a paragraph is to mark a pause, setting the paragraph apart from what precedes it. If a paragraph is preceded by a title or subhead, the indent is superfluous and can therefore be omitted.[3]
>
>The Elements of Typographic Style states that "at least one en [space]" should be used to indent paragraphs after the first,[3] noting that that is the "practical minimum".[4] An em space is the most commonly used paragraph indent.[4] Miles Tinker, in his book Legibility of Print, concluded that indenting the first line of paragraphs increases readability by 7%, on the average.[5]

**Comment by poire-z** [comment]
> Professionally printed material in English typically does not indent the first paragraph, but indents those that follow. 

But that's not something that I've seen in french printed books.

> You (might) know my opinion: it should be p+p {text-indent:1em} (or 1.2em, whatever). That'll work to prevent any unwanted indents in tables just the same as anywhere else (e.g., after a heading, after a list, after a blockquote, etc., etc., etc.).

Well, I understand you.
But my point with my question is not to play designer or publisher and find styles that are pleasant, or conforming to good typography practices, or would look good with unstyled HTML. That's what may have happened a bit over the years with our current epub.css (or its ancestors) where EPUBs were not that popular/styled (we may keep that for legacy mode).

Rather the opposite: **going more neutral**, as web browsers are, so our design preferences don't go in the way of publishers intentions (our design preferences may go into Style tweaks thus).

If a publisher wants to use `p+p {text-indent:1em}` , and assume a standalone `p` has no indent (like in web browers), I'm ok to remove `p {text-indent:1em}` from our epub.css (even if I like it, and I will have to use a style tweak to get it back when a publisher has not set it. But at least, I'll see what the publisher intended.
(Same for your _Before H1 seems fairly sensible_ - sensible as a design choice? or sensible as _obviously, H1 in page mode would cause a page-break for any normal person/publisher_ ? That, I don't know, cause I've only seen web browsers which don't do page splitting :)

The `margin-top: 1em; margin-bottom: 1em;` for P is more tedious. I've never seen that in books, and I guess it makes sense in web browsers with a large reading area, so I don't know if it shouldn't be considered a web design choice :)

Anyway, given the number of EPUBs I have that have classes named calibre1 calibre2... I guess most publishers make/tweak/test their EPUBs on Calibre, and we may want to look at its user agent stylesheet?

> PS I don't really understand all of these different render modes. Except possibly for the page overflow it sounds like I just want web and nothing but web (okay, and legacy I suppose).

Well, so why do you want `legacy`? Because it's a sane fallback. But you'll want `flat` mode instead (a similar but a bit nicer fallback), where everything degrades nicely as it used to on KOReader.
We haven't had much complaining about rendering issues, because it degrades to something that makes everything readeable (no style widths, only margins, so text mostly takes all page width; no style height, so no blank vertical area, super nice for reading).

But bring support for styles width and height (needed for sizing floats, which would be used only with floats in `book` mode), and you suddently get `width: 50%` (a possible good intent from the publisher) and `width: 640px` (a really bad choice from a publisher or generating tool) ensured ! and you're constrained, and you want back your full width. `web` or `news` won't allow that, or you'll have to kill widths and heights with style tweaks - but then, your floats are messed up. So `book` mode makes sense as an intermediate fallback.

For most books, all these render mode will give the same result, so it will feel a bit like a not useful toggle (i found floats in no more than 3-5% of my EPUBs).
But I don't just read EPUBs, I sometimes read saved webpages that can have more messy resulting styles, and having intermediate degradation levels is nice (also because my implementation will have bugs :) and I am lying with _web: renders are web browsers do_, cause we're far from that :)

**Comment by poire-z** [comment]
Another thing I remember. Once, a cover page was showing like:
```txt
      Author

      Title
Subtitle

     Publisher
```
The whole thing was wrapped in `<CENTER>`, with Headings (H2,H3) used for Author, Title and Publisher, except the Subtitle was wrapped in a P.
And our `P {text-align: justify;}` was killing the CENTER, aligning it to the left as no justification was needed.

So, P shouldn't have any text-align, and should just inherit from our `body {text-align: justify;}` (which I guess we could keep).

50% of the rendering glitches I've seen over the last 2 years were not actually crengine bugs, but caused by that kind of extra stuff we have in our epub.css (that hopefully we can solve with style tweaks).

**Comment by Frenzie** [comment]
> Rather the opposite: going more neutral, as web browsers are, so our design preferences don't go in the way of publishers intentions (our design preferences may go into Style tweaks thus).

Web browsers are by no means neutral. What you refer to as neutral here is American typewriter-based letter layout.

> The margin-top: 1em; margin-bottom: 1em; for P is more tedious. I've never seen that in books, and I guess it makes sense in web browsers with a large reading area, so I don't know if it shouldn't be considered a web design choice :)

You definitely need either the indent or the margin.

> (Same for your Before H1 seems fairly sensible - sensible as a design choice? or sensible as obviously, H1 in page mode would cause a page-break for any normal person/publisher ? That, I don't know, cause I've only seen web browsers which don't do page splitting :)

H1 indicates a new section. In your typical LaTeX style, for example, `\section{}` will come with a page break. If you don't want a pagebreak before H1, chances are you're using H1 wrong.

> Well, so why do you want legacy? Because it's a sane fallback.

Actually I don't want legacy; for me personally you can strip it right out, same for non-HarfBuzz rendering. ;-)

**Comment by poire-z** [comment]
> You definitely need either the indent or the margin.

OK, so I guess it we get rid of the indent, we should have these margins for a P to not be just a DIV.
It might be the first thing publishers are killing in their own styles if they don't want that.

> If you don't want a pagebreak before H1, chances are you're using H1 wrong.

Well, it's not me, but many publishers that are doing it wrong then, and Calibre too:

![image](https://user-images.githubusercontent.com/24273478/59329580-805a8880-8cef-11e9-9310-43109763ca3a.png)

KOReader would currently badly show this on 3 pages, because of its `H1 {page-break-before: always;}` (and the `page-break-after: avoid` is not breaking that - the specs indicates `always` wins over `avoid` - and calibre shows it the same if you remove them).
Well, Calibre seems to even not care about `{page-break-before: always;}` when there is content between them, it would still show them all on the same page with:

![image](https://user-images.githubusercontent.com/24273478/59331902-54da9c80-8cf5-11e9-938f-cace335e5f8c.png)

I spent quite some time having the `DocFragment {page-break-before: always;}` (which Calibre and other software are ensuring - a DocFragment seems to implicitely always start a new page) plays well with a followup `H1 {page-break-before: always;}` and generate a single page break (margins collapsing into a single one, so a single carrier of a page break) - but I can't do anything about avoiding that with consecutive H1 (if we keep `page-break-before: always`) as the specs say it should make multiple pages.

So, I guess if we want to allow new pages on H1 for single file document (plain html files), which would have no other implicite way to make page splits, we should use:
```css
h1 { page-break-before: always; }
DocFragment h1 { page-break-before: auto; } /* so, only when in EPUBs */
```

> Web browsers are by no means neutral

OK, but wording aside, do you understand my reasons for opening this issue?

**Comment by Frenzie** [comment]
> Well, it's not me, but many publishers that are doing it wrong then, and Calibre too:

In an EPUB context that would generally be its own `.xhtml` (DocFragment) with an associated page break, right? So it's largely a moot point. :-)

I'm not necessarily arguing to keep it, but it's a default that makes sense nonetheless. Your suggested solution of distinguishing between plain HTML and EPUB may be about as close to ideal as we can get with average real-world HTML documents. In a perfect HTML5 world everyone would probably use `<section>`.

We could also consider something like:

```css
h1:first-child { page-break-before: always; }
```

That way you'd catch a bunch of HTML5 sections as well pre-HTML5 sections along the lines of `<div><h1>`, presumably without too many false positives albeit with more arguable false negatives.

Perhaps it should be specified a little more strictly still, like `div>h1:first-child, section>h1:first-child`, because I wouldn't be surprised if people wrote weird stuff like `<span><h1></h1></span>`. Then again, someone who might write `<span class="bla"><h1></h1></span>` might just as well write `<div class="bla"><h1></h1></div>`.

> OK, but wording aside, do you understand my reasons for opening this issue?

Several of the styles have always struck me as oddly deviant and we've resolved most or all of that, but the paragraph deviation is by far the most sensible of the lot, especially prior to userstyles. What's generally expected is of course something more along these lines:

https://www.w3.org/TR/CSS2/sample.html
https://www.w3.org/TR/html5/rendering.html

**Comment by cramoisi** [comment]
I didn’t have the time right now to read everything but please don’t get rid of the text indent :) or don’t put it too far. French novels ( and any work of fiction)  need them and you can’t count on the publisher to get them right (because they use various units which are not supported or not right on a e-reader)

**Comment by Frenzie** [comment]
@sebastien I think the out of the box experience might be best with a default enabled userstyle (without !important) to that effect.

But userstyles are there no matter what. :-)

**Comment by cramoisi** [comment]
@Frenzie : Yup you are right It’s better in every ways...(and Sebastien is indeed my first name but you just ping somebody else :D  )

**Comment by Frenzie** [comment]
Whoops, sorry `@sebastien`!

**Comment by frankyifei** [comment]
if  there is not a standard publisher's styles we can work on. maybe just
follow most widely used epub viewer's behaviour like calibre viewer.

Frans de Jonge <notifications@github.com> 于 2019年6月13日周四 上午6:09写道：

**Comment by Frenzie** [comment]
I think calibre just goes with the standard QtWebKit stylesheet or in any case doesn't deviate from it much.

**Comment by poire-z** [comment]
Well, dumping a few related urls:

Specs suggesting rendering:
https://www.w3.org/TR/CSS2/sample.html
https://www.w3.org/TR/html5/rendering.html, with a resulting usable css:
https://github.com/FriendsOfEpub/WillThatBeOverriden/blob/master/ReadingSystems/html5/html5.css

Calibre (viewer?) rendering:
https://github.com/kovidgoyal/calibre/blob/master/resources/templates/html.css
with possibly http://trac.webkit.org/browser/trunk/Source/WebCore/css/html.css 

Collection of authoring tools and reader CSS:
https://github.com/FriendsOfEpub/WillThatBeOverriden
Looking at what's available there shows there is a mix of the 2 different paragraph styles (sometimes even in different products by the same vendor). So, I guess any serious publisher should include in its style some kind of reset/overrides if he wants its book fine


```https://github.com/w3c/publ-epub-revision/issues/672``` _Defining a minimal default stylesheet in the epub spec_ (including links to other issues) really interesting, and shows what a mess EPUB styling has become :)

https://github.com/readium/readium-css/tree/master/docs for how Readium go at stuff (it's still really unclear to me what this readium stuff is...)
https://github.com/readium/readium-css/tree/master/docs/i18n-samples some sample EPUBs and control pictures for RTL & other writings.

**Comment by poire-z** [comment]
So, having tested html5.css and some calibre css, switching between them and our epub.css had zero impact on the few publishers' EPUBs I tested that with, so I guess serious publishers really do reset/specify how they want stuff.
But it has an ugly impact on our Wikipedia EPUBs :) where I did not reset much.

Anyway, on a non/little-styled EPUB or HTML, I prefer our current epub.css, the others bring too much margin/spacing (like indentation in nested list items) - and, my preferences asides, may give too much of a change for our users.
I find our epub.css quite pleasant (or I'm just too used to it).

So I won't touch much of our epub.css, and may be we can provide a html5.css to allow people to quickly switch/have a try at the web rendering standard.

So, proposed changes to epub.css:
1) remove `text-align: center` from H1...H6, because it looks like publisher rarely specify/reset it to `text-align: left`. Should I let it be centered in legacy mode, for people who would really like that? Or just add a Style tweak to provide that?
2) remove `text-align: justify` from P: this should just be inherited from container (including CENTER). By default, it would inherit from our `body {text-align: justify;}`
3) have `H1 {page-break-before: always}` cancelled when DocFragment is an ancestor, as discussed above.
4) remove `page-break-before: always ` for H2 and H3. Should I let them in legacy mode for people who are used to it and may have some curated document with that? Or just via an added Style tweak?

Some other less critical non-standard things in our epub.css are the background color on TH and CAPTION, and a `text-align: center` for TH that no other CSS does. And calibre and html5.css do a bit of `vertical-align: middle` and `vertical-align: inherit` for table elements, that I don't feel like testing if we would support that well.

**Comment by Frenzie** [comment]
> remove text-align: center from H1...H6

A style tweak probably makes more sense but overall it seems like a fairly insignificant detail to me. :-)

**Comment by poire-z** [comment]
Proposed above changes have been made in #299.

The proposed trick:
`DocFragment h1 { page-break-before: auto; } /* so, only when in EPUBs */`
wasn't a good solution: it was preventing a publisher `h1 { page-break-before: always; }` from working, because of its higher specificity (a selector with 2 elements wins over one with a single element).

So, I had to implement and use:
```css
/* Don't break page on headings in EPUBs: publishers may not expect it,
 * as most EPUB renderers only break page on a new DocFragment. */
h1 {
    -cr-only-if: -epub-document; /* only if NOT EPUB document */
        page-break-before: always;
}
h2, h3 {
    -cr-only-if: legacy -epub-document;
        page-break-before: always;
}
```
