### ISSUE TITLE
Hyphenation with (em)-dashes?

### ISSUE THREAD

**Issue by Frenzie** [koreader/crengine#295]
I saw real hyphenated as re-al today, due to being followed by an em-dash.

![Screenshot_20190615_105924](https://user-images.githubusercontent.com/202757/59549372-c49e9080-8f5c-11e9-93f3-e64bb1dc94ea.png)

```html
<!DOCTYPE html>
<html>
<head>
<title>em-dash</title>
</head>
<body>
real—real—real—real—real—real—real—real—real—real—real—real—real—real—real—real—real—real—real—real—real—real—real
</body>
</html>
```

**Comment by poire-z** [comment]
You're not saying which hyph algo/dict you are using, and what are the hyphenation left/right limits.
English US vs UK would give different results:

English US seems to allow a hyphen between e-a:
```
word to hyphenate: ' real '
  hyph pattern matched: real 00100 on real  000000
  hyph pattern matched: eal 0040 on eal  01000
Hyphenate: re-a|l  r0e1-a4|l0
```
while English UK doesn't:
```
word to hyphenate: ' real '
  hyph pattern matched: rea 0004 on real  000000
  hyph pattern matched: re 020 on real  000400
  hyph pattern matched: ea 002 on eal  20400
Hyphenate: real  r2e0a4l0
```

Also, your test case might be considered a super long word, with no space opportunity to have split on, it might just be working with a super long word, possibly overflowing some `MAX_WORD_SIZE 64` and having some stuff not working as usual.
The em-dash being not considered like a space a split opportunity (it does not seem to have a specific behaviour, unlike unicode hyphen or the minus sign which get flagged with `LCHAR_DEPRECATED_WRAP_AFTER` and can be a break opportunity in some cases), I guess a split may then happen anywhere.

So, not obvious if it's a line splitting algo issue, or some hyphenation algo issue, or some specific hyph dict issue.
Might be easier to work directly with the paragraph you saw that in.
Here's a small patch to hyphman.cpp so it outputs (as seen above) what it is asked to hyphenate, and its final propositions: [hyph_word_dump.diff.txt](https://github.com/koreader/crengine/files/3293010/hyph_word_dump.diff.txt)

**Comment by Frenzie** [comment]
> You're not saying which hyph algo/dict you are using

Unless otherwise specified, default (US).

> Also, your test case might be considered a super long word, with no space opportunity to have split on

Okay, so just get rid of a couple of em dashes. The behavior doesn't change one way or the other. (And in any case, if an em-dash isn't considered a word splitting opportunity *that is the bug*! ;-) )

```html
<!DOCTYPE html>
<html>
<head>
<title>em-dash</title>
</head>
<body>
real real real real real real real real real real real real—real real real real real real real real real real real—real real real
</body>
</html>
```

**Comment by poire-z** [comment]
Well, if there's no space around the em dash, if it is sticking 2 words together, I guess it should not be a regular split opportunity: what it carries stuck should be fully at end of line or start of next line (unless the stuck word can be themselves hyphenated).

But it may be a DEPRECATED one, if a regular hyphen is (that's old code I have forgotten about, that may get used only in some extrem situation - I wrote about that in https://github.com/koreader/koreader/issues/2806#issue-223660083).

But if you're using EnglishUS, `re-al` is allowed, and in that case, it works as it should: breaking at e-a is authorized, and so prefered to anything else, because stuff is stuck anywhere else.

So, may be you want to fix the EnglishUS dict :)

**Comment by Frenzie** [comment]
A regular dash can stick words together, yet it allows for line breaks even though an em dash separates them by definition? Ideally people would use thin spaces around em dashes.

**Comment by poire-z** [comment]
> an em dash separates them by definition?

Well, I dunno, I never typed myself a em-dash :)

And I've always seen them in french text surrounded by normal space (and maybe no-br-spaces at occasion).

But reading https://en.wikipedia.org/wiki/Dash and https://www.thepunctuationguide.com/em-dash.html, it says some suggest not using spaces... (so, it might not be a publisher bug) and it's used for so many things, not just separating words or parts of sentences...

We could allow wrap after, but it may also be used at start of quote attribution, eg:
`[...]without sacrifice.—Mahatma Gandhi`

And:
> In Spanish, em dashes can be used to mark off parenthetical phrases. Unlike in English, the em dashes are spaced like brackets, i.e., there is a space between main sentence and dash, but not between parenthetical phrase and dash

The current code would handle that spanish thing nicely I think.

So, it does not look to me like easy handling, like just flagging it with `LCHAR_ALLOW_WRAP_AFTER` would be. Would need a little more inspection of the context... and do or not that specific stuff only when not a single surrounded space, and what if there's some puncuation on a side... and studying that Wikipedia article to see if some simple rules would cover most usages :|

We have this, so I hope we are handling them correctly as least when they are surrounded by thin spaces:
https://github.com/koreader/crengine/blob/37e29d42f74e39d3667f372c8fe4fd04085e07e4/crengine/src/lvfntman.cpp#L831-L839

**Comment by Frenzie** [comment]
Looks like Firefox does en dashes but not em dashes.

https://wiki.mozilla.org/Gecko:Line_Breaking#Breaking_after_hyphens

**Comment by poire-z** [comment]
> https://wiki.mozilla.org/Gecko:Line_Breaking#Breaking_after_hyphens

Nice find. There may be other stuff to flag with `LCHAR_ALLOW_WRAP_AFTER` according to it:

> The white spaces of ASCII are common breakable points. We defined white spaces are:
    U+0020 (SPACE)
    U+0009 (CHARACTER TABULATION)
    U+000D (CARRIAGE RETURN)
    U+2000 (EN QUAD)
    U+2001 (EM QUAD)
    U+2002 (EN SPACE)
    U+2003 (EM SPACE)
    U+2004 (THREE-PER-EM SPACE)
    U+2005 (FOUR-PER-SPACE)
    U+2006 (SIX-PER-EM SPACE)
    U+2008 (PUNCTUATION SPACE)
    U+2009 (THIN SPACE)
    U+200A (HAIR SPACE)
    U+200B (ZERO WIDTH SPACE)
    U+3000 (IDEOGRAPHIC SPACE)

We might revamp all this when we look at using utf8proc for categorizing chars.

**Comment by poire-z** [comment]
As @Frenzie in this issue, and @noembryo in https://github.com/koreader/koreader/issues/5191 , expected a break on EM-DASH, we could just, in the lvfntman.cpp snippet above, add a thing for it:
```diff
--- a/crengine/include/lvstring.h
+++ b/crengine/include/lvstring.h
@@ -26,6 +26,7 @@
 #define UNICODE_NO_BREAK_SPACE   0x00a0
 #define UNICODE_HYPHEN   0x2010
 #define UNICODE_NB_HYPHEN   0x2011
+#define UNICODE_EM_DASH     0x2014
 #define UNICODE_CJK_IDEOGRAPHS_BEGIN 0x3041
 #define UNICODE_CJK_IDEOGRAPHS_END 0x02CEAF
 #define UNICODE_CJK_IDEOGRAPHIC_SPACE 0x3000
--- a/crengine/src/lvfntman.cpp
+++ b/crengine/src/lvfntman.cpp
@@ -834,9 +834,10 @@ static lUInt16 char_flags[] = {
      (ch<48?char_flags[ch]: \
         (ch==UNICODE_NO_BREAK_SPACE?LCHAR_IS_SPACE: \
         (ch==UNICODE_HYPHEN?LCHAR_DEPRECATED_WRAP_AFTER: \
+        (ch==UNICODE_EM_DASH?LCHAR_DEPRECATED_WRAP_AFTER: \
         (ch==UNICODE_ZERO_WIDTH_SPACE?LCHAR_ALLOW_WRAP_AFTER: \
         (ch==UNICODE_THIN_SPACE?LCHAR_ALLOW_WRAP_AFTER: \
-         0)))))
+         0))))))

 struct LVCharTriplet
 {
```
With `LCHAR_DEPRECATED_WRAP_AFTER `, it gets a bit less chances of being used for line break than other candidates, but it would still be used in extreme (relatively :) situations (this does help in @noembryo text sample case).

Should I go at that?

And replace the 2 last ones to include the range from U+2000 to U+200B, excluding U+2007 ("figure space", I guess used in numbers to separate thousands) to be `LCHAR_ALLOW_WRAP_AFTER`?

**Comment by Frenzie** [comment]
It's not clear to me why Firefox thinks an en-dash deserves a line break and an em-dash doesn't, so fine by me. It was pretty much a singular occasion for me though. :-)

**Comment by poire-z** [comment]
Ah, so I should also add as DEPRECATED_WRAP_AFTER the others suggested on that Firefox page?
https://wiki.mozilla.org/Gecko:Line_Breaking#Breaking_after_hyphens
U+058A (ARMENIAN HYPHEN)
U+2010 (HYPHEN)
U+2012 (FIGURE DASH)
U+2013 (EN DASH)

Hoping that by using DEPRECATED_WRAP_AFTER, we don't have to check for the 4 bullet points on that page after the list :)

**Comment by Frenzie** [comment]
We already do HYPHEN of course, but yes. ;-)
