### ISSUE TITLE
Ticks of the progress bar 

### ISSUE THREAD

**Issue by vimalaguti** [koreader/crengine#335]
Hi,
I noticed the top bar is much more comfortable than the bottom one.
But - as far as I can understand - the ticks have no meaning; while in the bottom one are correct. (see the picture)
And with "correct" I mean each dot is a chapter start, so I get with a glance how many pages to the chapter end.
At the same time I cannot use the bottom progress bar because it has no space: with a few items added, the bar can use half of the width (of the portrait e-ink display)
![Screenshot from 2020-03-23 20-42-56](https://user-images.githubusercontent.com/25081309/77357063-d0b74a00-6d47-11ea-8d94-5cfa3990fa25.png)

I use koreader from a pocketbook, but on my laptop the result is the same.

**Comment by poire-z** [comment]
Some previous observations about our various ways of ticks in:
https://github.com/koreader/koreader/issues/5848#issuecomment-584766009
https://github.com/koreader/koreader/issues/5500

As for the bottom progress bar, you can make it 2-lines with the various options in the menu, so the progress bar itself can take the full width, and you can have the other items above or below it. https://github.com/koreader/koreader/pull/5442

(Better to keep issues and questions in koreader/koreader than in koreader/crengine, for more visibility.)

**Comment by Frenzie** [comment]
Gitter chat here btw: https://gitter.im/koreader/koreader?at=5e78846ec8f8c4425597fce0

**Comment by vimalaguti** [comment]
thanks that explains everything!

**Comment by poire-z** [comment]
With https://github.com/koreader/koreader/pull/6236 and this morning nightly, top progress bar should have the same ticks as the bottom progress bar.
