### ISSUE TITLE
Support for max-width

### ISSUE THREAD

**Issue by Jellby** [koreader/crengine#360]
I understand crengine doesn't support the `max-width` property (and presumably `max-height`)? At least that's what the koreader source says... If that's the case, here's a feature request: Add support for `max-width`. Without it, elements (e.g. images) styled with that property may look overblown and the general feel is that the rendering is broken.

**Comment by poire-z** [comment]
I wished we had that too sometimes. Never really cared about adding support for it, mostly because we're a bit short on available slots for more properties (https://github.com/koreader/koreader/issues/6345#issuecomment-653682435) and it didn't feel essential.
But may be one day.

In order of priority/need, which do you think would be the more needed:
```
max-width
min-width
max-height
min-height
```

**Comment by Frenzie** [comment]
@poire-z I think max-width and max-height are probably more important than the reverse, but I also think their presence would strongly imply that min-width and min-height were also available.

**Comment by Jellby** [comment]
max might be more important than min, because not fitting the screen is worse than being too small (unless it becomes too small to see at all).
width might be more important/usable than height, since the available width tends to be more easily accessible than the available height.
But having some and not the others would be pretty weird. I'd be OK (for now) with not being able to set `!important" for these properties, if that's the showstopper.

**Comment by poire-z** [comment]
> because not fitting the screen is worse than being too small 

In case it helps (and it should, it often did for me):

<kbd>![image](https://user-images.githubusercontent.com/24273478/87953014-ccf3c400-caaa-11ea-9da5-c6d8c01e3558.png)</kbd>

So, if stuff overflows the screen (which is a "feature" of "web" mode), switch from "web" to "book". (I think I saw cases where this didn't work, in web page dumps, so it might not be 100% up to what it says on twisted content).

(More details about the differences between these rendering modes at https://github.com/koreader/koreader/blob/201d3d8ad1c9e6432283439e3c14abfd9569bc2f/frontend/apps/reader/modules/readertypeset.lua#L321-L354)

**Comment by poire-z** [comment]
> mostly because we're a bit short on available slots for more properties (koreader/koreader#6345 (comment)) 

@pkb @NiLuJe : following @pkb suggestion at https://github.com/koreader/koreader/issues/6345#issuecomment-653720509 , I came up with this (not yet going over 64 bits, but ready for when needed):
(going with lUInt32 slots as that's the prefered size on ARM - and it allows testing right away it will work when we'll need 3 slots)

```diff
--- a/crengine/include/lvstyles.h
+++ b/crengine/include/lvstyles.h

-/* bit position (in 'lUInt64 important' and 'lUInt64 importance' bitmaps) of
- * each css_style_rec_tag properties to flag its '!important' status */
-// enum css_style_rec_important_bit : lUInt64 {  <= disliked by clang
+/* bit position (in 'lUInt32[] important' and 'lUInt32[] importance' bitmaps)
+ * of each css_style_rec_tag properties to flag its '!important' status */
 enum css_style_rec_important_bit {
-    imp_bit_display               = 1ULL << 0,
-    imp_bit_white_space           = 1ULL << 1,
-    imp_bit_text_align            = 1ULL << 2,
- [...]
-    imp_bit_content               = 1ULL << 59,
-    imp_bit_cr_hint               = 1ULL << 60
+    imp_bit_display = 0,
+    imp_bit_white_space,
+    imp_bit_text_align,
+ [...]
+    imp_bit_content,
+    imp_bit_cr_hint
 };
+#define NB_IMP_BITS 61 // The number of lines in the enum above: KEEP IT UPDATED.
+
+#define NB_IMP_SLOTS    ((NB_IMP_BITS-1)>>5)+1
+// In lvstyles.cpp, we have hardcoded important[0] ... importance[1]
+// So once NB_IMP_SLOTS becomes 3 when IMP_BIT_MAX > 64, add in lvstyles.cpp
+// the needed important[2] and importance[2]. Let us know if we forget that.
+#if (NB_IMP_SLOTS != 2)
+    #error "NB_IMP_SLOTS != 2, some updates in lvstyles.cpp (and then here) are needed"
+#endif

@@ -103,8 +111,5 @@ struct css_style_rec_tag {
     lUInt32              hash; // cache calculated hash value here
-    lUInt64              important;  // bitmap for !important (used only by LVCssDeclaration)
-                                     // we have currently below 61 css properties
-                                     // lvstsheet knows about 83, which are mapped to these 61
-                                     // update bits above if you add new properties below
-    lUInt64              importance; // bitmap for important bit's importance/origin
-                                     // (allows for 2 level of !important importance)
+    lUInt32              important[NB_IMP_SLOTS];  // bitmap for !important (used only by LVCssDeclaration)
+    lUInt32              importance[NB_IMP_SLOTS]; // bitmap for important bit's importance/origin
+                                                   // (allows for 2 level of !important importance)
     css_display_t        display;
@@ -165,4 +170,4 @@ struct css_style_rec_tag {
     , hash(0)
-    , important(0)
-    , importance(0)
+    , important{} // zero-initialization of all array slots
+    , importance{}
     , display( css_d_inline )
@@ -226,10 +231,12 @@ struct css_style_rec_tag {
     //  important bitmap management
-    bool isImportant( css_style_rec_important_bit bit ) { return important & bit; }
-    void setImportant( css_style_rec_important_bit bit ) { important |= bit; }
+    bool isImportant( css_style_rec_important_bit bit ) { return important[bit>>5] & (1<<(bit&0x1f)); }
+    void setImportant( css_style_rec_important_bit bit ) { important[bit>>5] |= (1<<(bit&0x1f)); }
     // apply value to field if important bit not yet set, then set it if is_important
     template <typename T> inline void Apply( T value, T *field, css_style_rec_important_bit bit, lUInt8 is_important ) {
+        int slot = bit>>5;        // 32 bits per LUint32 slot
+        int sbit = 1<<(bit&0x1f); // bitmask for this single bit in its slot
         // is_important is 2 bits: (high_importance, is_important) (see lvstsheet.cpp)
-        if (     !(important & bit)     // important flag not previously set
+        if (     !(important[slot] & sbit)     // important flag not previously set
               || (is_important == 0x3)  // coming value has '!important' and comes from some CSS parsed with higher_importance=true
-              || (is_important == 0x1 && !(importance & bit) ) // coming value has '!important' and comes from some CSS parsed
+              || (is_important == 0x1 && !(importance[slot] & sbit) ) // coming value has '!important' and comes from some CSS parsed
                                                                // with higher_importance=false, but previous value was not set from
@@ -238,4 +245,4 @@ struct css_style_rec_tag {
             *field = value; // apply
-            if (is_important & 0x1) important |= bit;   // update important flag
-            if (is_important == 0x3) importance |= bit; // update importance flag (!important comes from higher_importance CSS)
+            if (is_important & 0x1) important[slot] |= sbit;   // update important flag
+            if (is_important == 0x3) importance[slot] |= sbit; // update importance flag (!important comes from higher_importance CSS)
         }
[ similar in      inline void ApplyAsBitmapOr( css_length_t value, css_length_t *field, css_style_rec_important_bit bit, lUInt8 is_important ) { ]

--- a/crengine/src/lvstyles.cpp
+++ b/crengine/src/lvstyles.cpp
@@ -47,6 +47,6 @@ lUInt32 calcHash(css_style_rec_t & rec)
         rec.hash = ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((
-           (lUInt32)(rec.important >> 32)) * 31
-         + (lUInt32)(rec.important & 0xFFFFFFFFULL)) * 31
-         + (lUInt32)(rec.importance >> 32)) * 31
-         + (lUInt32)(rec.importance & 0xFFFFFFFFULL)) * 31
+         + (lUInt32)rec.important[0]) * 31
+         + (lUInt32)rec.important[1]) * 31
+         + (lUInt32)rec.importance[0]) * 31
+         + (lUInt32)rec.importance[1]) * 31
          + (lUInt32)rec.display) * 31
@@ -117,4 +117,6 @@ bool operator == (const css_style_rec_t & r1, const css_style_rec_t & r2)
     return
-           r1.important == r2.important &&
-           r1.importance == r2.importance &&
+           r1.important[0] == r2.important[0] &&
+           r1.important[1] == r2.important[1] &&
+           r1.importance[0] == r2.importance[0] &&
+           r1.importance[1] == r2.importance[1] &&
            r1.display == r2.display &&
@@ -315,4 +317,6 @@ bool css_style_rec_t::serialize( SerialBuf & buf )
     buf.putMagic(style_magic);
-    ST_PUT_UI64(important);         //    lUInt64              important;
-    ST_PUT_UI64(importance);        //    lUInt64              importance;
+    buf << important[0];            //    lUInt32              important[0];
+    buf << important[1];            //    lUInt32              important[1];
+    buf << importance[0];           //    lUInt32              importance[0];
+    buf << importance[1];           //    lUInt32              importance[1];
     ST_PUT_ENUM(display);           //    css_display_t        display;
@@ -376,4 +380,6 @@ bool css_style_rec_t::deserialize( SerialBuf & buf )
     buf.putMagic(style_magic);
-    ST_GET_UI64(important);                                 //    lUInt64              important;
-    ST_GET_UI64(importance);                                //    lUInt64              importance;
+    buf >> important[0];                                    //    lUInt32              important[0];
+    buf >> important[1];                                    //    lUInt32              important[1];
+    buf >> importance[0];                                   //    lUInt32              importance[0];
+    buf >> importance[1];                                   //    lUInt32              importance[1];
     ST_GET_ENUM(css_display_t, display);                    //    css_display_t        display;
```
(As expected, I needed tests with the python interpreter to check bits and rotations and results... as I'm as bad with bit arithmetic than with children arithmetic...)
(Seems to work: no hash mismatch, no loss in load and rendering times.)

Does that looks fine to you? Or would you bring even more bitwise black magic?

**Comment by NiLuJe** [comment]
@poire-z:

You can just stick an `imp_bit_max` at the tail of the enum, and define NB_IMP_BITS to `imp_bit_max` instead of having to keep track of it ;).

**Comment by poire-z** [comment]
> You can just stick an imp_bit_max at the tail of the enum, and define NB_IMP_BITS to imp_bit_max instead of having to keep track of it ;).

I had this idea and tried it ! :) Turned out the C preprocessor has no idea about enum (only the compiler does), so with `#define NB_IMP_SLOTS    ((imp_bit_max-1)>>5)+1` , I was getting NB_IMP_SLOTS=1 :/

No specific comment about the bitwise stuff?

**Comment by NiLuJe** [comment]
Oh, right >_<".

Nope, the rest looks sound for an uint32_t ;).

**Comment by johnbeard** [comment]
`max-width` is very important in Wikisource ebooks, as it's often used to "constrain" elements to a certain width on wide screens. IF `max-width` isn't supported, and a wide 'width' is set, lots of content spills off the screen.

**Comment by poire-z** [comment]
> lots of content spills off the screen.

Until it's supported, switch `Render mode` from `web` to `book` when that happens. And set it to default to `book` it you have to do that a lot, there's not much differences except allowing such overflows.

**Comment by poire-z** [comment]
References:
https://developer.mozilla.org/en-US/docs/Web/CSS/max-height
https://www.w3.org/TR/CSS2/visudet.html#min-max-widths
https://drafts.csswg.org/css-sizing-3/

As with regular width & height, various contexts and ways. (Not yet re-reading the whole things...)

> width might be more important/usable than height, since the available width tends to be more easily accessible than the available height.

Indeed, we always have the container width to guess the inner width if it's a %.
For height, we don't, and they most often adjust to content.
Width/Height % are not related to the viewport/screen height, right?
For images, I think crengine ensures they never are larger than the screen.

For thoughts, @Jellby @johnbeard : in which contexts did you missed/noticed that support wasn't there (and so, I guess it's where you want it first)?
A) regular block inside regular block (main flow)
B) sizing of floats and inline-block (secondary flows)
C) images ?
D) tables ? (CSS2.1 says their effects on table stuff is undefined)
E) others ?

and do the specified min/max-width had absolute sizes (px...), font-relative sizes (em) or % ?

**Comment by Jellby** [comment]
> Width/Height % are not related to the viewport/screen height, right?

No, there's `vh` and `vw` for that. But if there are no parent containers with specified width, width % should refer to the body width (which should be screen minus margins/padding), and it could be argued that a height % should refer to the screen/page height (although I believe the specs say it should be ignored).

> For images, I think crengine ensures they never are larger than the screen.

I've seen images cut in two pages (in paged mode), but I think they're SVG-wrapped.

> For thoughts, @Jellby @johnbeard : in which contexts did you missed/noticed that support wasn't there (and so, I guess it's where you want it first)?

I missed that particularly in images, which I set with something like `max-width: 50%`.
For instance, an author photograph in the the title page. I don't want it full-screen, and I don't want it larger than its native resolution, hence the `max-width`. Sometimes it happens to be a picture with good resolutio, so it's displayed full-page and looks awful (i.e., as if the sytlesheet was being ignored).

**Comment by poire-z** [comment]
> I missed that particularly in images, which I set with something like max-width: 50%.

You set that on the image itself ? or on its block (DIV) container ?
I think "style=width: 50%" on an image itself would scale it to 50% of the native image size. Does max-width behave differently ?

**Comment by Jellby** [comment]
I'd have to double check, but I think on the image itself, with a class:
```
img.photo { max-width: 50%; }
```
I don't think any percent should ever be related to the native size (I mean, according to the specs), it's one of the common pitfalls.

**Comment by johnbeard** [comment]
@poire-z quite a lot of stuff in A and B, I think, which are generally used to prevent the content "falling off" the page with `max-width:100%;`.

Also quite a few things use `max-width:XXem;` to prevent a block getting too wide, often used for tables of contents and some small text blocks (usually along with `margin:auto;` to put it in the centre). Generally not a huge issue on an e-reader, as opposed to a 1080p+ browser window.

I've also seen it used for "sidenotes" where a little block of text is floated into the left or right of the page and you want them to wrap rather than extending across the page.

**Comment by Frenzie** [comment]
Sidenote for sidenotes, those often expand to full size at smaller widths
(which may apply to at least some ereaders).

**Comment by johnbeard** [comment]
This is an example of a sidenote style I've seen 
``` css
.sidenote {
  margin: 0.5em;
  max-width: 9em;
  float: left;
}
```

**Comment by poire-z** [comment]
When these are applied on a IMG, do you think I am right in my understanding:

A) it can apply directly on the image, no effect on the surrounding containers - and neither surrounding containers sizes apply on the sizing of the image

B) when sizing an image, the algo is as simple as:
1 get native image w and h
2a if both CSS width: and height: use them instead of the native image ones, possibly losing native aspect ratio
2b if only CSS width or only CSS height: use it instead of the native image one, infere the other one by keeping aspect ratio
We then have the image final w/h and final aspect ratio.
(This is already done by crengine)

After this:
3a if any of min/max-width/height, just adjust the image final w/h **while keeping aspect ratio** so these constraints are ensured
3b haven't looked yet how to resolve conflicts at this point if any :) but may be give up aspect ratio?

Thoughts?

**Comment by Jellby** [comment]
I'm not sure what you mean in A). An image can definitely have an effect on surrounding contaiters (e.g. a div with border, that contains an img, the size of the div depends on the size of the img), and vice-versa (e.g. an img with width: 30%, its size depends on the container's width).

As for B, my impression is that CSS (at least version 2) is pretty stupid when it comes to keeping aspect ratios: it works if you specify *only* width or height (with or without max/min), but specifying both will probably not give the expected result, that's why we use SVG wrappers for cover images. A detailed description can probably be found in https://www.w3.org/TR/CSS22/visudet.html#min-max-widths, but maybe it's best to prepare a sample HTML+CSS document with all possible cases and see what a decent browser does.

**Comment by Frenzie** [comment]
> A) it can apply directly on the image, no effect on the surrounding containers - and neither surrounding containers sizes apply on the sizing of the image

I'm not quite sure what you mean, but the specific behavior would depend on whether the image is inline/inline-block/block/table-cell, etc. I don't think whether it's an image or not is particularly relevant?

**Comment by poire-z** [comment]
OK, sorry, with A, I just meant that the fact that there are min/max-width/height , or that there aren't any, does not change anything in how the image interact with its containers.
That is, we can only care about these min/max-width/height where we currently care about the native image size and its style's width:/height: , where we compute the image "computed/used width and height".
And that I don't have to care about min/max-width/height anywhere else.
Does that sound right?

crengine may still later reduce width (keeping A/R) so it does not overflow its paragraph/page width, but that should be all)

**Comment by poire-z** [comment]
Implemented in #409. with a few limitations:
- no support for height/min-height/max-height in `%`
- max-height supported only on images (but still not if `%`)
- no support for any of them on table cells (complicated, I did not have the heart to go risk playing with the table layout algorithm)

**Comment by johnbeard** [comment]
This appears to fix most of the use cases I see around. Thank you!

**Comment by Jellby** [comment]
Is this in 2021.01? I have a picture with `img.photo { max-height: 12em }` which doesn't seem to be working...

**Comment by poire-z** [comment]
No it isn't. Still waiting for a few days (and some release hot fixes) to bump this up to into frontend, so we get another month before next release to be sure it's fine.
