### ISSUE TITLE
ODF (odt) format support.

### ISSUE THREAD

**Issue by SilverGreen93** [koreader/crengine#367]
As the engine currently supports reading and displaying docx XML documents, I am surprised to find that it cannot open odt files.
Is odt support a thing that will be added?
It would be nice to support the Open formats for documents.
Thanks!

**Comment by Frenzie** [comment]
I guess you'd have to ask @pkb ;-) (Or at least, I'm not terribly interested since you can use export to EPUB.) See https://github.com/koreader/crengine/pull/314

**Comment by pkb** [comment]
I'm not ready to spend much time on ODT. I will check how complex it is. If I'll find it easy to implement :) I'll probably make it.

**Comment by SilverGreen93** [comment]
Ok, thank you both for reply. You are right that both docx and odt can be converted to epub and transferred to KOReader. It is just nice to have the ability to open odt directly like docx.

**Comment by Frenzie** [comment]
Well, how about that. Thanks @pkb! :+1: 
https://github.com/buggins/coolreader/pull/164
