### ISSUE TITLE
24bit support in LVColorDrawBuf

### ISSUE THREAD

**Issue by ezdiy** [koreader/crengine#382]
Mainly a perf issue for https://github.com/koreader/koreader/issues/6479. To make CFA blits reasonably fast (division-free), the source image buffer must be in 24bit RGB byte color format. With that the blitter determines shingle factor once, and bumps byte offset by 1 mod 3 for each scanline. Rest of koreader can be coerced into this, except CRE. Currently I'm going with 32->24 alpha stripping conversion step in the blitter for simplicity, but it bloats memory use/hogs memory bandwidth needlessly.

**Comment by NiLuJe** [comment]
It's likely to still end up looking like that somewhere in the pipeline, IIRC, at least image decoding is already always RGB32.

I don't recall everywhere the bitdepth comes into play, but at least the lvdrawbuf bits are "trivial", if boring and numerous ;).

**Comment by ezdiy** [comment]
Yea, now looking at it, the conversion happens the same for RGBA->GRAY on CRE level too. Ie the conversion happens no matter what. Guess alpha stripping in blitbuffer then amounts to same as if CRE did the same thing it does for grayscale. 24bit would matter only if the color buffer, and all image processing truly used 24bit with no alpha. No idea if there's amount of C++ template abstraction to allow for that, or the engine is hard addicted to 32bit int bit fiddling by hand.

**Comment by NiLuJe** [comment]
From what I recall of the last time I fiddled with this (i.e., I may very well be getting things wrong ^^), the LVColor* stuff is pretty keen on using uint32_t (i.e., RGB32, 32bpp), and LVGray* uint8_t (i.e., Y8, 8bpp) as the "native" internal pixel format.

**Comment by ezdiy** [comment]
FWIW, most of the slowness (for me) arises from BB{24,32}->BB8 being sucky on pocketbook due to lua blitter being far too naive (blitDefault). So specializing that first is probably more productive venue than trying to bend everything into outputting desired FB format.

**Comment by NiLuJe** [comment]
Ah, now I get why you were wondering about toggling the C blitter ;p.

I don't know if you can even go through the memcpy fastpaths on PB, or if you have to deal with a forced rotation that'd prevent it.

But, FWIW, both should be at feature-parity. The C blitter is just a tad faster, but the main interest is that it doesn't bog down the JIT into doing crazy stuff sometimes, and that's it's no longer at the mercy of said JIT, so the performance is consistent, which is especially noticeable on said rotated codepaths.

**Comment by ezdiy** [comment]
> The C blitter is just a tad faster

Indeed the problem isn't code as such, but cache pressure due to rotation.

> if you have to deal with a forced rotation that'd prevent it anyway.

With BB8->BB8, things usually just so-so fit (32 bytes cache + 1000 scanlines = 32k dcache spam per scanline). With RGBA it catches fire because you run out of cache (on input side) much sooner, and end up trashing the cacheline repeatedly for same pixel.

The specialization I have in mind is for the single orientation (portrait->hw landscape) only, with getPixelP bumping on Y axis, loading up 8 words (full cacheline), doing pixel conversions on those. This should ease the cache pressure somewhat.
