### ISSUE TITLE
Previous margin carried over to footnote

### ISSUE THREAD

**Issue by Jellby** [koreader/crengine#388]
A footnote section with:
```
<h1>Notes</h1>

<aside class="footnote" id="note1" epub:type="footnote">
```
where the `<h1>` has a bottom margin and the `<aside>` has top margin, results in the margin being rendered in the in-page footnote. which at least in the attached example looks really bad. I guess this is a consequence of collapsing margins and copying the rendered footnote to the page, but in case it can be fixed, here is the report.

Screenshots with `kodev run -s=aura`. Red background on `<body>` and blue background on `<aside>`, for clarity:

![Screenshot_20201025_153235](https://user-images.githubusercontent.com/7943459/97110078-7c0df000-16d7-11eb-9c8a-2aafadaf4b2a.png)
![Screenshot_20201025_153436](https://user-images.githubusercontent.com/7943459/97110115-b081ac00-16d7-11eb-8796-933dfd27ea2c.png)

The second footnote is ok, no extra margins:

![Screenshot_20201025_153450](https://user-images.githubusercontent.com/7943459/97110117-b11a4280-16d7-11eb-96c0-f5fea78d98ff.png)

And two footnotes in the same page are fine too. Probably because the forced pagebreaks makes them lose their margins...

![Screenshot_20201025_153545](https://user-images.githubusercontent.com/7943459/97110144-cc854d80-16d7-11eb-84ee-791945fd9bf3.png)

ePub filie within the zip: [test.zip](https://github.com/koreader/crengine/files/5434906/test.zip)

**Comment by poire-z** [comment]
> I guess this is a consequence of collapsing margins and copying the rendered footnote to the page

Yes, that's exactly it. Previously mentionned at https://github.com/koreader/koreader/issues/6344#issuecomment-672635110

I quite often get that ugly first in-page footnote... but I haven't found a clean way to solve it :/ 
(It was solvable with FB2, as we're half of the publisher.)

On your screenshot, there's the added effect that the first footnote has not enough room and is splitted onto 2 pages - usually, I just get some extra space beween the footnote line and the first footnote text.

**Comment by Jellby** [comment]
Would it make sense to just ignore the vertical margins for the footnotes when copying them in-page? I'm guessing margins appear as separate "lines", so it should be possible to copy only the "content" lines and not the margins... Some extra margins (not given by the original css could be added if there are several footnotes on the same page.

**Comment by Jellby** [comment]
> > Would it make sense to just ignore the vertical margins for the footnotes when copying them in-page?
> 
> Dunno. With EPUBs, footnotes can have any kind of layout, including inner vertical margin if it contains multiple blocks, like some P and then a BLOCKQUOTE. Deciding to drop them generally might mess the publisher layout.

Inner margins, yes. But do we want any margin before the actual content? We already have the line and some small space.

> > Some extra margins (not given by the original css) could be added if there are several footnotes on the same page.
> 
> I would not like this added margin between footnotes :)

I meant, if that is the reason for not discarding the margin.

> What I tried with the patch mentionned in the issue linked above is to push vertical margin before entering the footnote - which might have been fine for the first footnote, but may be it had ugly effects on the next ones (I don't remember why I abandonned it - but I'm quite sure there was a reason :)

> But yes, with the above current code, and when trying that patch, I guess I was OK with dropping any start and end padding & margin of each slice we consider a footnote (and may be I abandonned it because I felt that was eventually not OK :)

You've probably thought/experimented with it more than I, but it seems to me it should be OK (after all, in-page footnotes are already kind of a hack, so it probably cannot be perfect in all circumstances). And bottom margin is being discarded, isn't it? At least in the test document there is no bottom margin (or border) in the in-page footnotes (which is fine).

> One case I could think about is a multiple paragraphs footnote which has margin/padding between its paragraphs - and dropping the ones at start and end would made the inner blank noticable, while each footnoe would be stuck to the previous and next one. But we would already have that if that is ensured with padding.

But they are already dropped (see below), it's only the first footnote that gets it.

> Something to try, with style tweaks that enable in-page footnotes, is to add a 1px padding-top

Right, or `page-break-before: always`. But those alter the appearance of the notes in their native section. Forcing 1px padding also breaks cases with non-zero padding.

Actually, I just noticed the tweak is enforcing `margin: 0 !important;`, which has probably the same intention, except when margins come from other elements, as in this case... So it seems to me that just something like your patch (as far as I understand it) would be better, and maybe this margin override could be removed?

**Comment by poire-z** [comment]
> And bottom margin is being discarded, isn't it? At least in the test document there is no bottom margin (or border) in the in-page footnotes (which is fine).

Because the bottom margin collapses into/is carried by the next element (with its top margin if any) - or into a blank line if next element has some padding-top.

> So it seems to me that just something like your patch (as far as I understand it) would be better, and maybe this margin override could be removed?

Well, here's my patch from 9 months ago: [isFootNodeBodyPushVMargin1.diff.txt](https://github.com/koreader/crengine/files/5435603/isFootNodeBodyPushVMargin1.diff.txt)
```diff
--- a/crengine/src/lvrend.cpp
+++ b/crengine/src/lvrend.cpp
@@ -6561,8 +6561,15 @@ void renderBlockElementEnhanced( FlowState * flow, ldomNode * enode, int x, int

                 // Enter footnote body only after padding, to get rid of it
                 // and have lean in-page footnotes
-                if ( isFootNoteBody )
+                if ( isFootNoteBody ) {
+                    // If no padding were added, add an explicite 0-padding so that
+                    // any accumulated vertical margin is pushed here, and not
+                    // part of the footnote
+                    if (padding_top==0) {
+                        flow->addContentLine(0, RN_SPLIT_AFTER_AVOID, 0, true);
+                    }
                     flow->getPageContext()->enterFootNote( footnoteId );
+                }

                 // recurse all sub-blocks for blocks
                 int cnt = enode->getChildCount();
@@ -6958,8 +6965,15 @@ void renderBlockElementEnhanced( FlowState * flow, ldomNode * enode, int x, int

                 // Enter footnote body after padding, to get rid of it
                 // and have lean in-page footnotes
-                if ( isFootNoteBody )
+                if ( isFootNoteBody ) {
+                    // If no padding were added, add an explicite 0-padding so that
+                    // any accumulated vertical margin is pushed here, and not
+                    // part of the footnote
+                    if (padding_top==0) {
+                        flow->addContentLine(0, RN_SPLIT_AFTER_AVOID, 0, true);
+                    }
                     flow->getPageContext()->enterFootNote( footnoteId );
+                }

                 // We have lines of text in 'txform', that we should register
                 // into flow/context for later page splitting.
```
It applies with no pb to current master.
I just tested it with ~10 books, without noticing any issue - so I must have missed the right book :) 
Feel free to test it for some time, to validate it causes more good than harm.

**Comment by poire-z** [comment]
I'm about to make a PR. Should I add this patch in?
Somehow, it looks logical and in-line with what we do when there is some padding.
And may be with this in the wild, I'll be able to find back my memory of why I decided to abandon it :/

**Comment by NiLuJe** [comment]
I rarely use in-page footnotes, but it does look sound on paper ;).

**Comment by Frenzie** [comment]
> Somehow, it looks logical and in-line with what we do when there is some padding.

Not going to read the whole thread atm, but treating margin (more or less) the same as padding sounds sensible.
