### ISSUE TITLE
Picking upstream lString16/lChar16 => lString32/lChar32 massive renaming ?

### ISSUE THREAD

**Issue by poire-z** [koreader/crengine#389]
This is regarding picking https://github.com/buggins/coolreader/pull/183 by @virxkane .

I think we should pick it, just because:
- not picking it will make CR and KR massively hard to keep sync'ed (and more work for each side when picking future work)
- @NiLuJe hates the stuff being named *16 when it is actually stored as *32 :) (I personally don't mind that)

But I'll be sad picking it because:
- it will screw my git history/blame playground
- I'm so used writting lString16 / lChar16 - that I'll have a hardtime for some time - and for this reason, I think we should _not_ pick the 2nd commit that re-introduced lString16/lChar16 being char16_t for use with WINAPI stuff - but also with some/any filepath in lvstream.cpp.
- it will be quite some work to pick

It's not as easy to just apply it, because CR/upstream had previously splitted lvstring.cpp/.h and lvfntman.cpp into multiple unit files, one per class (and that, I don't want to pick it - or it's the end of me working with git history/blame :/)

So, I would have to re-do what you @virxkane did.
Is it really just a matter of massive string renamings:
- `lString16` > `lString32`
- `lChar16` > `lChar32`
- `L"` > `U"` (this one will hurt my heartstory :) , many changes in unrelated places)
- `L'`  > `U'` (single chars, I think you missed this one, or at least in a few places).

and:
- some internal lvstring.cpp variable renaming like chunk16 to chunk32
- a few myvar16 > myvar32 variable names renamings elsewhere

@virxkane : any specific places where more work and attention is needed that I should be aware of ?

Regarding not picking the 2nd commit:
the only real common code using the re-added *16 stuff is lvstream.cpp. Any issue in there not picking that and having it keep using *8 or *32 - given the fact we're not building for Windows (and that I hardly ever touch lvstream.cpp)?

**Comment by NiLuJe** [comment]
Throwing a pebble in the pond: if we're renaming the typedef, why not get rid of it and use wchar_t directly?

**Comment by NiLuJe** [comment]
But, barring my rock throw, all the yes ^^.

AFAICT, the second commit is "fairly" self-contained, so I don't see why we should omit it, even if it's gloriously useless for 99.9998% of our use-cases ;).

**Comment by virxkane** [comment]
> @virxkane : any specific places where more work and attention is needed that I should be aware of ?

Also don't forget about lString16Collection. But I've forgotten about lString16HashedCollection.

> ... Is it really just a matter of massive string renamings: ...

and cs16() -> cs32()
macro _16 -> _32



> It's not as easy to just apply it, because CR/upstream had previously splitted lvstring.cpp/.h and lvfntman.cpp into multiple unit files, one per class (and that, I don't want to pick it - or it's the end of me working with git history/blame :/)

It is very difficult to work with such giant files, for example, let's take lvtinydom.cpp, about 19 thousand lines, several dozen classes, if they were in separate files, I would open them in separate tabs and work, but now I have to scroll many times this file, and constantly getting lost, it is very inconvenient, I think not only for me.
And if the cost of splitting this file into several is complicating the work of git blame, then I'm ready to pay it.

**Comment by NiLuJe** [comment]
Another good thing is that `char32_t` is *always* unsigned, unlike `char` (and possibly `whar_t` itself, too?).

**Comment by poire-z** [comment]
> the second commit is "fairly" self-contained, so I don't see why we should omit it

Because I _will_ write again lString16 - and I'd rather have a compiler error than an OK compile and having some mess up at runtime (or not notice any, as I don't read emojis or stuff greater than U+FFFF :)

> if we're renaming the typedef, why not get rid of it and use wchar_t directly?

Because some of us are used to read and write lChar16, and the transition to reading/writting lChar32 should be bearable - unlike bringing more low-level C42/C1664 stuff I don't care about :)

> (EDIT: Oh, unless the secondary drive was actually using char32_t on Windows instead of wchar_t).

Yes, that's the main idea.

**Comment by NiLuJe** [comment]
I'm mildly worried than not picking it now will only make things worse down the line, whereas checking for stray lChar16 automatism shouldn't be too hard ;).

**Comment by poire-z** [comment]
> and cs16() -> cs32()
macro _16 -> _32

OK, thanks.
So you're confirming the first commit is really just renamings? No real brain work was needed once/after you found out what needed a massive rename ?

----
Off-topic (not my current war, let me first get done with that lString32 one :):

> It is very difficult to work with such giant files

Personally, I don't mind the giant files. I know it makes it hard to get into all the stuff for a newcomer.
After a few years with them, I'm fine, I know where to find stuff :)
What's a bit more sad than a giant file is that the things, class and methods for a same class are all intermixed up... but re-ordering them would also kill git blame (which I'm not ready to give up - at least on the things like lvrend/lvtinydom I'm still practicing quite often).
(One thing it would help with is the compilation time when you change one line to lvtinydom.cpp :)

> I would open them in separate tabs

I usually search for strings/names, so, having more tabs would have me search for the string/name in multiple tabs :) (I use "vim" and have one single file open).

**Comment by poire-z** [comment]
> I'm mildly worried than not picking it now will only make things worse down the line

I'm quite not (if @virxkane confirms that): the main idea is that we should never anymore use lString16/lChar16 in the main code - only at edges when it's needed for WinAPI.
I just have my doubts about the need for them in lvstream.cpp - I haven't checked if the updated thingies in lvstream.cpp are only used with the Windows frontends - or not.

**Comment by virxkane** [comment]
> So you're confirming the first commit is really just renamings? No real brain work was needed once/after you found out what needed a massive rename ?

Yes, this is a trivial refactoring with manual revision.

> I'm quite not (if @virxkane confirms that): the main idea is that we should never anymore use lString16/lChar16 in the main code - only at edges when it's needed for WinAPI.

Yes, but there is one very strange idea to use the new lString16 to save memory, most books have enough BMP from Unicode, perhaps on the fly, if necessary, re-encoding from UTF-16 to UTF-32, but I did not seriously think about it :)

**Comment by virxkane** [comment]
> After a few years with them, I'm fine, I know where to find stuff :)

And now everyone who wants to make changes to it needs to spend several years of their life? :)

> What's a bit more sad than a giant file is that the things, class and methods for a same class are all intermixed up

This is also a good reason to change something.

**Comment by NiLuJe** [comment]
Well, I could take the memory saving argument further and argue for plain (unsigned) `char`s and UTF-8, because it makes more sense on that front for LGC ;).

Granted, nothing's really wired to deal with chars and UTF-8, but, still ;p.

**Comment by virxkane** [comment]
UTF-16 is still a more convenient encoding, for BMP you don't need to recode anything at all, unlike UTF-8. It's like a compromise between UTF-8 and UTF-32.
https://www.unicode.org/versions/Unicode13.0.0/ch02.pdf#G11153
These are not some serious plans, but simply ideas that most likely will never be realized.

**Comment by poire-z** [comment]
> I just have my doubts about the need for them in lvstream.cpp - I haven't checked if the updated thingies in lvstream.cpp are only used with the Windows frontends - or not.

OK, the updated thingies are indeed in `#if WIN32` , so I don't mind not picking them.

So, spent a few hours with boring search and replaces...
At the end, I compared our diffs by file (for those we have in common), which allowed me to correct a few `"format is HTMU"` :) (because of the massive L"A" => U"A" replacements): I just have a bit more `L > U` renames, a few more variables like filename16 that I renamed to filename32.
@virxkane : here's [CRvsKR_16to32.diff.txt](https://github.com/koreader/crengine/files/5445702/CRvsKR_16to32.diff.txt) (totally not apply'able, just to be read to see what changed where, and to apply manually) in case you want to catch up. (Not including the lString32HashedCollection stuff, that I did but that you know about).

**Comment by virxkane** [comment]
> @virxkane : here's [CRvsKR_16to32.diff.txt](https://github.com/koreader/crengine/files/5445702/CRvsKR_16to32.diff.txt) (totally not apply'able, just to be read to see what changed where, and to apply manually) in case you want to catch up. (Not including the lString32HashedCollection stuff, that I did but that you know about).

@poire-z, thank you!
But I found some issues:
```diff
diff -Naur virx/lvstream.cpp.patch my/lvstream.cpp.patch
--- virx/lvstream.cpp.patch	2020-10-27 12:59:16.152975010 +0100
+++ my/lvstream.cpp.patch	2020-10-27 12:58:40.513663506 +0100
@@ -197,7 +197,16 @@
          if ( !fn.empty() )
              lastch = fn[fn.length()-1];
          if ( lastch!='\\' && lastch!='/' )
-@@ -1659,7 +1659,7 @@ class LVDirectoryContainer : public LVNamedContainer
+@@ -1593,7 +1593,7 @@ public:
+ 
+                 if ( (dwAttrs & FILE_ATTRIBUTE_DIRECTORY) ) {
+                     // directory
+-                    if (!lStr_cmp(pfn, L"..") || !lStr_cmp(pfn, L".")) {
++                    if (!lStr_cmp(pfn, U"..") || !lStr_cmp(pfn, U".")) {
+                         // .. or .
+                     } else {
+                         // normal directory
+@@ -1658,7 +1658,7 @@ public:
          FindClose( hFind );
  #else
          // POSIX
```
This is not a valid change - this code is Win32, pfn is of type wchar_t, so the string constant must actually be prefixed with `L`.

```diff
-@@ -2798,7 +2798,7 @@ class LVRarArc : public LVArcContainerBase
+@@ -2797,7 +2797,7 @@ class LVRarArc : public LVArcContainerBase
  {
  public:
  
 -    virtual LVStreamRef OpenStream( const wchar_t * fname, lvopen_mode_t mode )
-+    virtual LVStreamRef OpenStream( const lChar32 * fname, lvopen_mode_t mode )
++    virtual LVStreamRef OpenStream( const char32_t * fname, lvopen_mode_t mode )
      {
          int found_index = -1;
          for (int i=0; i<m_list.length(); i++) {
```
Base class (LVContainer) have function prototype signature `LVStreamRef OpenStream( const lChar32 * fname, lvopen_mode_t mode )`, so this diff is not correct, but by the way it doesn't change anything.

**Comment by poire-z** [comment]
OK, thanks, I'll revert that in a future PR (I remember I saw a mix of char32_t and lChar32 in your lvstream changes, it's possible I expected a single kind and I blindly updated some of them :)

**Comment by virxkane** [comment]
Well, I didn’t very carefully rename these things...

**Comment by virxkane** [comment]
> OK, thanks, I'll revert that in a future PR (I remember I saw a mix of char32_t and lChar32 in your lvstream changes, it's possible I expected a single kind and I blindly updated some of them :)

Also please don't forget https://github.com/koreader/crengine/pull/379#discussion_r495179318

**Comment by poire-z** [comment]
You mean you prefer it to become `lChar32((attr.length() & 0x7FFFFFFF) | 0x80000000)` - or is there something else related to this Char32 migration I missed?
(Feel free to do it if you have the time, I'll pick it with your other stuff.)

**Comment by virxkane** [comment]
> You mean you prefer it to become `lChar32((attr.length() & 0x7FFFFFFF) | 0x80000000)`

Yes, only about replacing "+1" to " | 0x80000000".

**Comment by poire-z** [comment]
> (Feel free to do it if you have the time, I'll pick it with your other stuff.)

OK, I'm doing it, as part of a PR where I pick your recent stuff.
So, it's mostly just 2 times:
```diff
-                    parsed_content << lChar32(attr.length() + 1); // (+1 to avoid storing \x00)
+                    parsed_content << lChar32(attr.length()|0x80000000); // (avoid storing \x00 when empty)
```
and 4 times:
```diff
-            lChar32 len = parsed_content[i] - 1; // (remove added +1)
+            lChar32 len = parsed_content[i] & 0x7FFFFFFF; // (remove bit added with |0x80000000)
```
Right ?

**Comment by poire-z** [comment]
Well, the above doesn't work as well as the initial simple +1 / -1 :/
The test case is a sufficiently large book that will have a cache file and has such `content:''`.
Clear cache, load, exit app, relaunch app. I should not get:
`CRE WARNING: cached rendering is invalid (stylesheet hash mismatch): doing full rendering`
but I get it again with the above fixes.
Even with a lots of casting and parenthesis :) : 
```diff
@@ -1141,3 +1141,3 @@ bool parse_content_property( const char * & str, lString32 & parsed_content)
                     parsed_content << U'a';
-                    parsed_content << lChar32(attr.length() + 1); // (+1 to avoid storing \x00)
+                    parsed_content << lChar32(((unsigned int)(attr.length()))|0x80000000); // (avoid storing \x00 when empty)
                     parsed_content << attr;
@@ -1230,3 +1230,3 @@ bool parse_content_property( const char * & str, lString32 & parsed_content)
                 parsed_content << U's';
-                parsed_content << lChar32(str32.length() + 1); // (+1 to avoid storing \x00)
+                parsed_content << lChar32(((unsigned int)(str32.length()))|0x80000000); // (avoid storing \x00 when empty)
                 parsed_content << str32;
@@ -1319,3 +1319,3 @@ void update_style_content_property( css_style_rec_t * style, ldomNode * node ) {
         if ( ctype == 's' ) { // literal string: copy as-is
-            lChar32 len = parsed_content[i] - 1; // (remove added +1)
+            lChar32 len = lChar32(((unsigned int)parsed_content[i]) & 0x7FFFFFFF); // (remove bit added with |0x80000000)
             res.append(parsed_content, i, len+2);
@@ -1324,3 +1324,3 @@ void update_style_content_property( css_style_rec_t * style, ldomNode * node ) {
         else if ( ctype == 'a' ) { // attribute value: copy as-is
-            lChar32 len = parsed_content[i] - 1; // (remove added +1)
+            lChar32 len = lChar32(((unsigned int)parsed_content[i]) & 0x7FFFFFFF); // (remove bit added with |0x80000000)
             res.append(parsed_content, i, len+2);
@@ -1370,3 +1370,3 @@ lString32 get_applied_content_property( ldomNode * node ) {
         if ( ctype == 's' ) { // literal string
-            lChar32 len = parsed_content[i++] - 1; // (remove added +1)
+            lChar32 len = lChar32(((unsigned int)parsed_content[i++]) & 0x7FFFFFFF); // (remove bit added with |0x80000000)
             res << parsed_content.substr(i, len);
@@ -1375,3 +1375,3 @@ lString32 get_applied_content_property( ldomNode * node ) {
         else if ( ctype == 'a' ) { // attribute value
-            lChar32 len = parsed_content[i++] - 1; // (remove added +1)
+            lChar32 len = lChar32(((unsigned int)parsed_content[i++]) & 0x7FFFFFFF); // (remove bit added with |0x80000000)
             lString32 attr_name = parsed_content.substr(i, len);
```

So, unless you or @NiLuJe see what's wrong in the above, I'd rather stay with the simple and safe +1/-1 and avoid the shady territory of the most significant bit where things are not clearly signed or unsigned to me :)

(The initial solution is https://github.com/koreader/crengine/pull/379/commits/80e77fb5706c00794dc914756986836e35e7b36c, which has since been migrated to lString32/lChar32.)

**Comment by virxkane** [comment]
Is there any converting this string to utf-8? If so, the code 0x80000000 cannot be used.

**Comment by NiLuJe** [comment]
@poire-z: Is there a chance to hit a value higher than `0x80000000`? Because that's the effective upper bound with it, while it's only `0x0xFFFFFFFE` with the +1/-1 trick.

**Comment by poire-z** [comment]
> Is there any converting this string to utf-8?

I don't think so, it's a pure lString32 used for storage, later serialized slot by slot cast'ed to lUInt32 into SerialBuf with:
https://github.com/koreader/crengine/blob/3bd3f2e6fee1780d601401128a2747a8a2058c32/crengine/src/lvstring.cpp#L4851-L4860

> Is there a chance to hit a value higher than 0x80000000? 

Zero chance I guess, it's the length of the '' part in a CSS bit `content: 'toto'`, so 4 there. So, it's always a small positive number that can be 0.

Well, if nothing jumps at your eyes, I guess we don't need to spend time at deuglyfying my +1/-1, which is not thay ugly after all, vs what I have above :)

**Comment by NiLuJe** [comment]
That *might* simply be exposing a bug somewhere because of high bits being set...

Is it possible to debug the mimstach (e.g., by printing the computed vs. expected cached value?), see if a pattern emerges?

Could you try with something like `^ 0xFFFFFFFF`, which will also set high bits for 0. Or simply reverse the current method (e.g., -1 -> +1, which will also underflow 0).

**Comment by NiLuJe** [comment]
Sidebar: that byte by byte excerpt seems over-engineered for no good reason?

Pointer arithmetic to the rescue:

```C++
*((lUint32*) (_buf + pos)) = n;
pos+=4;
```

Or, slightly more readable, maybe:

```C++
lUint32* p = _buf[pos];
*p = n;
post+=4;
```

**Comment by poire-z** [comment]
Well, I did some printf. The length are between 0 and 7, and I see stored and used
```
7 0x80000007
0 0x80000000
```
Nothing suspicious.

We do read the things stored in buf/_data with `int * p = _data;` (but many type mismatch if I changed that to `unsigned int * p = _data`. So, not bothering, we might even need to read negative int from it, dunno.

Tried with:
```diff
-                    parsed_content << lChar32(attr.length() + 1); // (+1 to avoid storing \x00)
+                    parsed_content << lChar32(attr.length() + 0x1000000); // (+1 to avoid storing \x00)
-            lChar32 len = parsed_content[i] - 1; // (remove added +1)
+            lChar32 len = parsed_content[i] - 0x1000000; // (remove added +1)
```
It works fine with:
```
0x1000
0x10000
0x100000
```
but it fails with:
```
0x1000000 (so, even with most significant 7 bits unset !)
0x10000000 (with the most significant 3 bits unset)
```
Strange :/ May be we have a lUInt8 shift somewhere, or a ++ with the wrong type... But well, can't see anything.

**Comment by NiLuJe** [comment]
Is all of that logic in lvstring.cpp, or is some of it spread elsewhere?

**Comment by NiLuJe** [comment]
Also, fails how? WHat does the mismatch look like with the printfs?

**Comment by poire-z** [comment]
> Is all of that logic in lvstring.cpp, or is some of it spread elsewhere?

No, for now (and later :), I'm just in lvstsheet.cpp.

> Also, fails how? What does the mismatch look like with the printfs?

Well, the end failure *was* `stylesheet hash mismatch` (before I added the +1/-1, but is now `style hash mismatch`, so something earlier and a bit more deeper in the style struct... (lvstyles.cpp, the way this lString32 content is copied into the struct, or something...).
There are too many hashes instances and kind to printf them. I did that kind of investigation in the past, but it's painful.

So, enough for me. I had hard times in the past fixing these mismatches. I don't know why this one would happen, I'd be curious to know why, but well, not worth more time spent.
Sticking to THE rule: If it's not broken, don't fix it :)

**Comment by NiLuJe** [comment]
Any (rough) pointers of where I might focus my eyes if I find time to look at this?

**Comment by poire-z** [comment]
Well, hashes, lString32... lvstyles.cpp's lUInt32 calcHash(css_style_rec_t & rec)

BUT, just realized I don't get this hash mismatch when just changeing font size and re-rendering. So, probably something with the serialization to cache:
`bool css_style_rec_t::serialize( SerialBuf & buf )`
does
`buf << content;` which is a lString32.

https://github.com/koreader/crengine/blob/3bd3f2e6fee1780d601401128a2747a8a2058c32/crengine/src/lvstring.cpp#L4871-L4884
does indeed do UnicodeToUtf8() as @virxkane suggested would be an issue.

That's why it works with 0x100000 but no more with 0x10000000 !
So, ok, if lString32 get to be serialized (so converted to utf8), better store only real unicode in it, not any arbitrary large lChar32/unsigned int.

Now, will these utf8<>unicode functions properly allow me to store values like 127, 128, 129... ? :/ 
https://github.com/koreader/crengine/blob/3bd3f2e6fee1780d601401128a2747a8a2058c32/crengine/src/lvstring.cpp#L3086-L3122
https://github.com/koreader/crengine/blob/3bd3f2e6fee1780d601401128a2747a8a2058c32/crengine/src/lvstring.cpp#L2970-L2994
Or are they values in unicode codepoints reserved just to not stumble in these conversions? (delegating this investigation :) I'm a bit not friend with binary arithmetic, thanks :)

**Comment by NiLuJe** [comment]
Anything below 0xFF is a 1:1 mapping to ASCII in UTF-8. (Which is why we prefer UTF-8 in Latin-speaking languages: no bytes wasted).

**Comment by poire-z** [comment]
Ok, just checked to be certain:
```c
    lString32 s = U"\x7E";
    lString32 t = U"\x7F";
    lString32 u = U"\x80";
    lString32 v = U"\x81";
    printf("%x %x\n", s[0], Utf8ToUnicode(UnicodeToUtf8(s))[0]);
    printf("%x %x\n", t[0], Utf8ToUnicode(UnicodeToUtf8(t))[0]);
    printf("%x %x\n", u[0], Utf8ToUnicode(UnicodeToUtf8(u))[0]);
    printf("%x %x\n", v[0], Utf8ToUnicode(UnicodeToUtf8(v))[0]);
```
gives
```
7e 7e
7f 7f
80 80
81 81
```
So, case closed:
- we understood why the mess with | 0x80000000
- we know to be careful when storing large integer in a lChar32 if it might be serialized to utf8
- and it turns out +1/-1 is just fine.
