### ISSUE TITLE
getPageMapLastPageLabel give the last page not the highest page

### ISSUE THREAD

**Issue by yparitcher** [koreader/crengine#398]
I have a book in which the publisher put the copyright etc at the end so the reference pages go like (1,2,5,6 ... 100, 3,4)

when i turn on reference pages the footer will say `10/4` as `4` is the last page, however it might make more sense to say `10/100` as the book has 100 pages, to do this would require reworking `getPageMapLastPageLabel` to not give the last page but rather the page with the highest #. this will probably be complicated as some books might not have numbers but titles.

@poire-z 
as i am not familiar with the crengine code, does it make sense when loading the pagemap to check each entry if it is the highest and store the result as a member of `class LVPageMap` and use that as the `LastPageLabel`?

**Comment by poire-z** [comment]
> does it make sense when loading the pagemap to check each entry if it is the highest and store the result as a member of class LVPageMap and use that as the LastPageLabel?

I don't think so. Not in crengine. In crengine, pagemap/pagemapitems are just the things we met: they are just a (title/label + xpointer) that we store without much brain work - and make available to frontend.
I don't think we need to have more than that in crengine: keep it simple there (so we don't have to bump it too often), and put the hard logic in frontend.

We have in cre.cpp: `getPageMapFirstPageLabel()` and `getPageMapLastPageLabel()` - that returns the first and the last items of the crengine list. May be that's the ones you want to fix, or rather: don't want to use :) 

So, I think any kind of stuff like what you want to do should (fortunately :) just be done in frontend/apps/reader/modules/readerpagemap.lua : that's where we attempt at converting the title/label string to something that looks like a page. So, it's there that you would parse and attempt to decide what can look the best as the last page or max page or number of pages.

So, yes, probably just `ReaderPageMap:getLastPageLabel()` - and yes, complicated to have something that would work just with everything. Probably hard to get right. What's the last page when there are `437` and `xxvii` among the titles/labels ?

> I have a book

If it's only 1 book, I wouldn't bother :) I guess 1/4 of the books I meet have one feature or another that does not work well (no TOC, in-page footnotes impossible to get working, only the cover as non-linear fragments...) Given that reference page numbers are even super rarer, I would just disable them if they look bad.
But there's room in the `Reference pages>` if you want to add another option to allow more complicated heuristics.

**Comment by yparitcher** [comment]
:( as i thought is is not simple. 
I am not interested enough to work on this (as you said so far it is just one book)
