### ISSUE TITLE
Something weird about the <script> element

### ISSUE THREAD

**Issue by Frenzie** [koreader/crengine#401]
[okhttp.html.zip](https://github.com/koreader/crengine/files/5719671/okhttp.html.zip)

I can't quite tell what's going on here at a glance, but it's not quite right since it's all inside the `<script>` element. According to the HTML validator the file is fine besides some duplicated IDs.
```
o.appendChild(a).innerHTML="<a id='"+u+"'></a><select id='"+u+"-\r\\' msallowcapture=''><option selected=''></option></select>",a.querySelectorAll
```

![Screenshot_2020-12-19_16-40-17](https://user-images.githubusercontent.com/202757/102693164-e5facf80-4218-11eb-88f1-654dbcd7d411.png)

![Screenshot_2020-12-19_16-37-37](https://user-images.githubusercontent.com/202757/102693144-b055e680-4218-11eb-97f7-edecc1892e0f.png)

**Comment by poire-z** [comment]
There's no specific parsing tweak when parsing SCRIPT - so, its content probably makes the XML/HTML parser stumble: when meeting the HTML tags inside the script, it probably auto closes SCRIPT and do stuff in some strange ways with what's after.
(Not interested in fixing that - until I myself meet that kind of stuff too often :)

**Comment by poire-z** [comment]
Although it could possibly be as simple as what I did for CDATA in https://github.com/koreader/crengine/commit/1332a7ff50d23fcde27369e18ed41c63185828bd : just consume text inconditionnally until we find `</script>` (with matching cases as the initial one).

**Comment by Frenzie** [comment]
That seems to be exactly what browsers do, if you remove the closing `</script>`.

**Comment by Frenzie** [comment]
And even if there are potentially some rare exceptions, I think the overall outcome would be greatly improved regardless if it's technically 100 % correct in a handful of edge cases.
