### ISSUE TITLE
Bug in lvstring.cpp

### ISSUE THREAD

**Issue by zwim** [koreader/crengine#412]
In https://github.com/koreader/crengine/blob/master/crengine/src/lvstring.cpp#L2512-L2515 s is not incremented, so the loop does not end.

Suggested change line in 2514: `n = n * 10 + ( (*s++)-'0' );`

**Comment by NiLuJe** [comment]
Or mirror the `lString8::atoi()` behavior which just adds an `s++;` on the next line ;).

**Comment by poire-z** [comment]
Indeed, looks like a bug in that bit of code.
But it seems not used anywhere, except in some CoolReader specific bit (I think): hist.cpp `ChangeInfo::fromString()`.
So, we shouldn't be able to trigger this bug on current KOReader, or can we?
If you're adding some new things that are using it, you may as well fix it while you add this thing.
