### ISSUE TITLE
`transparent` is a valid foreground color as of CSS Colors 3

### ISSUE THREAD

**Issue by johnbeard** [koreader/crengine#418]
In CSS Levels 1 and 2, `transparent` was not a "real" colour and could not be used for the foreground color (i.e. `color`). In [CSS Colors 3](https://www.w3.org/TR/css-color-3/#transparent), it's promoted to a real color:

> CSS3 extends the color value to include the ‘transparent’ keyword to allow its use with all properties that accept a <color> value. This simplifies the definition of those properties in CSS3. 

This means that the following:
```html
Before <span style="color:transparent;">transparent</span> After
```
should look like this:
![Sigil](https://user-images.githubusercontent.com/5386578/106884219-e8d25680-66d8-11eb-8a2f-bb30c35ff415.png)

In crengine, it has no effect:
![Koreader crengine](https://user-images.githubusercontent.com/5386578/106883997-aa3c9c00-66d8-11eb-90b4-a535cba8e4dd.png)

EPUB with the above:
[transparent-color.epub.zip](https://github.com/koreader/crengine/files/5925299/transparent-color.epub.zip)

**Comment by johnbeard** [comment]
Related? https://github.com/koreader/crengine/issues/176#issuecomment-478321727

**Comment by poire-z** [comment]
Yes, there is support for parsing *color: transparent.
But the handling for text drawing is something else - and it's just not like doing just as visibility:hidden.
If I understand your publisher hack from https://github.com/koreader/crengine/issues/417#issuecomment-773266704, you would expect the text glyphs to not be drawn (or be drawn with the same color as its background-color), but the decoration to still be drawn (so, with another color inherited from the parents, which we don't handle (and hard to do for the reasons explained at https://github.com/koreader/crengine/issues/417#issuecomment-773227639).

So, for this test case, if solving #418 (which might be easier) but not #417, you'll get holes in your text :/
