### ISSUE TITLE
[FR] Dual-page mode and title-page

### ISSUE THREAD

**Issue by zwim** [koreader/crengine#437]
Since you have implemented the **dual-page** option, I use that exclusively (on a Tolino 8 inch display). Thanks for that.

When opening a book, the title (cover-image) is rendered in the left column. On the right column the second page of the book follows, as it should be.

Would it be possible to show the titlepage of the book "fullscreen"? 

Or as an alternative, when opening a new book (in dual page mode) just show the title (cover-image) and after a tap start with the "title page / second page"?

Or as least preferable alternative allow two sets of settings for a book (settings1: as usual, settings2: for dual with smaller font, spacings ...)? So one could open the book in single column mode with settings1, look at the cover image go to page two and switch to  "two column" and settings2.

**Comment by poire-z** [comment]
> Would it be possible to show the titlepage of the book "fullscreen"?

Not easily. And your first page might not even include a cover.
(Or the EPUB could have a cover that does not make it to the first page of the book, like our Wikipedia EPUBs)
Even with FB2, where there is a specific handling of the cover page, this cover page is shown only on half the screen.
And given that you'll spend 0.2% of your reading time on the first page, this is not worth the thinking and coding time to find a solution :)
(And I don't think a solution should be implemented on the crengine side, which would be complex - rather some kind of hack on the frontend side, which I would even not be keen on.)

> Or as an alternative, when opening a new book (in dual page mode) just show the title (cover-image) and after a tap start with the "title page / second page"?

Well, that could be pure frontend code, launching an ImageViewer if there is a cover - but really, not worth the behaviour inconsistency (it happening only in 2 page modes, and getting rid of it with a swipe down unlike gesture to go to next page).
You can also do that from File Brower with a long-press on the book before opening it - so why bother?
And you can long-press on the half-screen cover to show the cover full screen in ImageViewer - so, again, why bother? :)

> Or as least preferable alternative allow two sets of settings for a book (settings1: as usual, settings2: for dual with smaller font, spacings ...)? So one could open the book in single column mode with settings1, look at the cover image go to page two and switch to "two column" and settings2.

You could handle these different sets of settings with our dispatcher/gestures/profiles plugins.

**Comment by zwim** [comment]
> And you can long-press on the half-screen cover to show the cover full screen in ImageViewer - so, again, why bother? :)
> You could handle these different sets of settings with our dispatcher/gestures/profiles plugins.

I will try those two, thanks.
