### ISSUE TITLE
[FR] Dynamically increase space to fit pageheight

### ISSUE THREAD

**Issue by zwim** [koreader/crengine#446]
Would it be possible to dynamically increase space between paragraphs and/or dynamically increase line spacing to fit the full pagehight? (Similar as it is done in LaTeX: paragraph margin +10%-5%, line separator +2%-1% or so)

As you can see in the image (especially noticeable in two column mode) the bottom of the text is not always aligned. 
When avoiding orphans/widows is enabled, this is a bit disturbing (not only in two column mode).

![Untitled](https://user-images.githubusercontent.com/36999612/126288055-7c8894ee-4946-42b4-9c29-ee2d876a6915.png)

**Comment by poire-z** [comment]
Hardly possible, the way crengine do things:

1) rendering, each block gets a x/y/h/w (that's what you see in "continuous/scroll" mode - slice-lines are added to some "page context" (for each text line, collapsed margins, padding, borders, table row, images), but there's zero notion of page yet at this point, so no way to do any adjustments to these lines height or margins/paddings.
2) page splitting: lvpagesplitter just process the lines in the "page context" to fit them in the target page_height: this makes a list of page with a starting y and the page height. At this point only you know you have pages with different heights. There is no retro action possible, nothing links back to the original boxes, and lines do not always link to any box (with collapsed margins, added space when clearing floats).
3) at drawing time, we have to draw a page: we get its y and height, and we walk down all imbricated block to get the ones that intersect with the page y/height, and ask each block (paragraphs+its containers) to draw themselves (borders, backgroung, their text and images).
It may all be so imbricated that you can't really do any counting/accounting of what can get some additional y-shifts to fill a bit more the page (could possibly be achieved in a normal page, but add tables, floats, fancy containers, and you may get all this quite messy). Additionally, text selection and highlights would be even harder to get adjusted to follow  these shifts done at drawing time.

So, very very complicated, and would need some kludge in many places.
May be for simple pages such as this one, using this style tweak could help, if you can bear the larger spacing ?
![image](https://user-images.githubusercontent.com/24273478/126311712-9751c518-1d4b-45e5-b042-63f9d355ceb4.png)

**Comment by zwim** [comment]
Thank you.

With the style-tweak ` p, li { margin-top: 0 !important; margin-bottom: 0 !important; } ` most pages look good. But the problem with orphans/widows remains.

![image](https://user-images.githubusercontent.com/36999612/126320214-b03db44f-2a0c-42ca-9106-4710a9bc359e.png)

**Comment by poire-z** [comment]
Just kill widows & orphans with the existing style tweak "Ignore publishers widows & orphans" (I always enable it when I notice publishers have set them).
It feels that adjusting line height/paragraph spacing to counteract these widows/orphans would feels uglier than seeing widows and orphans.
