### ISSUE TITLE
FR: text-shadow css support

### ISSUE THREAD

**Issue by mergen3107** [koreader/crengine#503]
Hi! Is it possible to add text-shadow support for css? I’d like to put shadows to title names in a book. 

Thanks!

**Comment by poire-z** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow

Probably too complex and niche (and rarely used in ebooks), and cosmetics only, to really happen :/

**Comment by Frenzie** [comment]
It's not that niche on the web, but yeah, on eink...

**Comment by mergen3107** [comment]
Here is an example of using shadows for title decorations. I found it quite attractive. Let me know what you think :D 

![Screenshot_20221229-171540](https://user-images.githubusercontent.com/6279855/210016216-0beca610-be76-4eba-8016-5d3b90098cc4.png)
