### ISSUE TITLE
Some page numbers are being displayed, instead of being caught and hidden

### ISSUE THREAD

**Issue by frank-murphy** [koreader/crengine#570]
In crengine/cr3gui/data/html5.css, there's an attempt to catch and hide pagebreaks displaying page numbers:

```
/* EPUB3 epub:type="pagebreak" may sometimes have the page number
 * as content: hide it. (Usually, its content is empty and the
 * page number is in a title= attribute.) */
span[type=pagebreak] {
    display: none;
}
```

This doesn't seem to match these spans, and hide them

**Comment by poire-z** [comment]
You'd need to show us your HTML and CSS, if you want to understand why they are not hidden.
And may be we won't want to act by default on your specific HTML & CSS because it would catch other stuff that we wouldn't want to hide. So, you may end up needing to use a book specific style tweak to hide them.

**Comment by frank-murphy** [comment]
Oh, I feel dumb. These are "hard-copy page numbers," not at all coming from the main xhtml and css, but from either the nav or the ncs file (this epub has both). I found the "Show reference page labels in margin" setting, and it all works as I would expect.

Sorry, I jumped into the css too fast.

**Comment by frank-murphy** [comment]
…but I can only see the Reference Pages menu on the Mac, not on the Android reader.

**Comment by frank-murphy** [comment]
Never mind. The Reference Pages menu item only shows up when an ePub that has them is open. I had expected it to always be there.

**Comment by frank-murphy** [comment]
Not a bug. User error
