### ISSUE TITLE
Update Codebase to C++ 20/17?

### ISSUE THREAD

**Issue by arjpar** [koreader/crengine#599]
I was wondering how receptive you all would be to updating the codebase to C++ 20 or C++ 17, if possible. I understand there are build constraints regarding support for specific platforms. I'm willing to submit a PR.

**Comment by benoit-pierre** [comment]
We're already mandating C++17 (for `constexpr`, see https://github.com/koreader/koreader-base/blob/master/Makefile.defs#L567). Anything newer is not going to be possible.

What do you want to update exactly? Be specific.

**Comment by Frenzie** [comment]
What specifically would you like to update and for which reason?

**Comment by poire-z** [comment]
> I was wondering how receptive you all would be

I'm not receptive at all.

**Comment by arjpar** [comment]
@benoit-pierre @Frenzie

> What do you want to update exactly? Be specific. [...] What specifically would you like to update and for which reason?

I was specifically thinking about updating as much of [`crengine/src`](https://github.com/koreader/crengine/tree/master/crengine/src) as possible to C++ 17, mainly because I was perusing the codebase, and (IIRC) it seemed like it would be more maintainable in modern C++ than the code it is now. But, being able to correctly translate old code into C++ 17, with no to minimal bugs, is doing a lot of heavy lifting. And it's a very ambitious idea, when it would be better to update small files that haven't been updated or used very infrequently.

The real question is do the benefits honestly outweigh the drawbacks? How much more maintainable would the modified codebase (let's assume all of crengine) be, compared to how it is now? Since everyone else in this thread is more experienced with this codebase than I am, I'd love to hear your thoughts.

I'm feeling the answer is: the benefits don't outweigh the drawbacks, it may cause more problems than it solves.

**Comment by poire-z** [comment]
> How much more maintainable would the modified codebase (let's assume all of crengine) be, compared to how it is now?

I don't know about C++ versions and what are the benefits (if any) of the changes (and I don't really want to know :)).
But as one of the few people that maintain crengine, I don't need any C++ new stuff, and I'd rather not see any gratuituous changes all over the place (moreover by someone not familiar with the big picture). It's already complex and brittle, and "git blame" is a must to "maintain" it (showing the real history of changes, I even do not fix bothering indentation issues to not mess with it).
So, yes, the answer is: the benefits don't outweigh the drawbacks.
