### ISSUE TITLE
Disable embedded fonts

### ISSUE THREAD

**Issue by j4w0r** [koreader/crengine#76]
It would be useful if we could disable embedded fonts in crengine so that koreader could override any embedded text font family preserving ebook's styles (if "embedded style" is enabled in koreader).

There are a few koreader's issues submitted regarding this topic:
- [Enhancement: Override ePub embedded text font family when embedded style is "on" #830](https://github.com/koreader/koreader/issues/830)
- [Disable embedded fonts #2048](https://github.com/koreader/koreader/issues/2048)
- [One default font for all books #2103](https://github.com/koreader/koreader/issues/2103)
- [Changing fonts should overwrite bundled EPUB-bundled CSS #2670](https://github.com/koreader/koreader/issues/2670)
- [txt.css always overwrites font setting #2779](https://github.com/koreader/koreader/issues/2779)

**Comment by poire-z** [comment]
It seems this feature is already available in crengine, but was not used by koreader.
I had a go at it, and it works, with a few caveats:
When you have in the book some styles with `font-family: "Some embedded font", serif;`, it indeed does not use the embedded font, but use one other font that it considers adequate for `serif`, which may not be the default font set in koreader.
This can be tested with current koreader by just adding in epub.css `; font-family: serif` to:
`p { text-align: justify; text-indent: 1.2em; margin-top:0em; margin-bottom: 0em }`, and disabling Embedded styles.
I haven't yet understand how crengine work that out, but we may have a go at using this feature, and see what more work may be needed on crengine side (like not applying any font-family from the css if EmbeddedFonts are disabled, or just ignore some values...)

**Comment by poire-z** [comment]
Done in https://github.com/koreader/koreader/pull/3149
